#!/usr/bin/env bash
# SessionStart: put the learnings index in front of every session, so no one re-walks a documented
# dead end. The index (.claude/learnings/INDEX.md) is regenerated by .claude/scripts/learnings_index.py
# whenever the learning-recorder writes an entry; each line is one entry's date, title and key lesson.
# stdout from a SessionStart hook is added to the session's context.
root="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
index="$root/.claude/learnings/INDEX.md"
[ -f "$index" ] || exit 0
entries=$(grep -c '^- ' "$index" 2>/dev/null); entries=${entries:-0}
echo "=== openproceedings learnings ($entries entries) — read the relevant ones before non-trivial work ==="
# Newest first, capped so a long journal cannot flood the context; the full index is one Read away.
grep '^- ' "$index" | head -40
[ "$entries" -gt 40 ] && echo "… $((entries - 40)) older entries in .claude/learnings/INDEX.md"
echo "Closing a task? /record-learnings is required before a PR (require-review.sh enforces it)."
exit 0
