import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // typescript-standards: no `any`; no @ts-ignore (@ts-expect-error only, with a reason).
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/ban-ts-comment": ["error", { "ts-expect-error": "allow-with-description" }],
      // The CSP allows inline scripts (src/lib/security-headers.ts), so HTML is never built from strings:
      // highlights are text nodes cut at the API's spans.
      "react/no-danger": "error",
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/api/schema.ts",
    // generated by @lezer/generator from query.grammar (npm run gen:grammar)
    "src/editor/lang/parser.ts",
    "src/editor/lang/parser.terms.ts",
  ]),
]);

export default eslintConfig;
