#!/usr/bin/env bash
# Case table for .claude/scripts/changelog.py (spec 08 §Release, decision-022). Each case builds a
# throwaway repo (real commits and v* tags, the backend and frontend manifests, docs/releases.toml) with the
# script copied in, feeds it a PR list with --prs (or a fake `gh` on PATH: no test reaches GitHub), and
# checks the exit status and the CHANGELOG.md it writes, or that a refusal wrote nothing.
# Usage: ./test-changelog.sh
set -u
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_PREFIX
SRC="$(cd "$(dirname "$0")/../../.." && pwd)"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
pass=0; fail=0
R="$TMP/r"
G=(git -C "$R" -c user.name=t -c user.email=t@example.org -c commit.gpgsign=false -c tag.gpgsign=false)

ok()  { pass=$((pass+1)); printf '  ok   %s\n' "$1"; }
bad() { fail=$((fail+1)); printf '  FAIL %s\n' "$1"; }

# versions <backend> <frontend>
versions() {
  printf '[project]\nname = "openproceedings"\nversion = "%s"\n' "$1" > "$R/backend/pyproject.toml"
  printf '{\n  "name": "frontend",\n  "version": "%s"\n}\n' "$2" > "$R/frontend/package.json"
}
# data <version> <tokenizer> <schema> <query> — append a releases table
data() {
  printf '[releases."%s"]\nindex_version = "0123456789ab"\nsnapshot_hash = "%s"\ntokenizer_version = "%s"\nschema_version = "%s"\nquery_version = "%s"\n\n' \
    "$1" "$(printf 'a%.0s' $(seq 1 64))" "$2" "$3" "$4" >> "$R/docs/releases.toml"
}
commit() { "${G[@]}" commit -q --allow-empty -m "$1" && "${G[@]}" rev-parse HEAD; }
# pr <number> <title> <merged_at> <sha> <base> <head> [head_repo]
pr() { printf '{"number":%s,"title":"%s","merged_at":"%s","merge_commit_sha":"%s","base":"%s","head":"%s","head_repo":"%s"}' \
  "$1" "$2" "$3" "$4" "$5" "$6" "${7:-o/r}"; }

# The standard repo: c1, c2 tagged v0.1.0 (0.1.0 has a data table), then c3, c4 untagged.
fresh() {
  rm -rf "$R" && mkdir -p "$R/.claude/scripts" "$R/backend" "$R/frontend" "$R/docs"
  cp "$SRC/.claude/scripts/changelog.py" "$R/.claude/scripts/"
  git init -q "$R" && versions 0.2.0 0.2.0 && : > "$R/docs/releases.toml" && data 0.1.0 2 2 2
  C1=$(commit c1); C2=$(commit c2); "${G[@]}" tag -a v0.1.0 -m v0.1.0; C3=$(commit c3); C4=$(commit c4)
  {
    echo "["
    pr 1  'feat: add the lexer' 2026-01-02T00:00:00Z "$C1" dev feat/lexer; echo ","
    pr 10 'feat: an earlier feature' 2026-01-01T00:00:00Z "$C1" dev feat/early; echo ","
    pr 2  'fix(query): keep NEAR <in> one [field]' 2026-01-03T00:00:00Z "$C2" dev fix/near; echo ","
    pr 9  'ci: pin actions' 2026-01-03T00:00:00Z "$C2" dev ci/pin; echo ","
    pr 3  'Read the archive*' 2026-01-04T00:00:00Z "$C3" dev fix/archive; echo ","
    pr 4  'feat!: drop the v0 route' 2026-01-05T00:00:00Z "$C4" dev feat/drop; echo ","
    pr 11 'Tidy the notes' 2026-01-05T00:00:00Z "$C4" dev misc-branch; echo ","
    pr 5  'Promote dev to main' 2026-01-03T00:00:00Z "$C2" main dev; echo ","
    pr 6  'chore: release 0.1.0' 2026-01-03T00:00:00Z "$C2" dev release/0.1.0; echo ","
    pr 7  'feat: stacked on the lexer' 2026-01-02T00:00:00Z "$C1" feat/lexer feat/x; echo ","
    pr 8  'docs: a note from a fork' 2026-01-04T00:00:00Z "$C3" main dev fork/r
    echo "]"
  } > "$TMP/prs.json"
}
run() { python3 "$R/.claude/scripts/changelog.py" --repo o/r --prs "$TMP/prs.json" "$@" > "$TMP/out" 2>&1; }

# expect <ok|err> <label> [args...] — the exit status; on err, also that CHANGELOG.md wasn't touched
expect() {
  local want="$1" label="$2" got before after; shift 2
  before=$(cat "$R/CHANGELOG.md" 2>/dev/null || echo "<none>")
  if run "$@"; then got=ok; else got=err; fi
  after=$(cat "$R/CHANGELOG.md" 2>/dev/null || echo "<none>")
  if [ "$got" = "$want" ] && { [ "$got" = ok ] || [ "$before" = "$after" ]; }; then ok "$label -> $got"
  else bad "$label -> $got (want $want$([ "$before" != "$after" ] && echo ', and a refusal changed CHANGELOG.md'))"; cat "$TMP/out"; fi
}
# has <label> <fixed string> / lacks <label> <fixed string> — in CHANGELOG.md
has()   { if grep -qF -- "$2" "$R/CHANGELOG.md"; then ok "$1"; else bad "$1: missing $2"; fi; }
lacks() { if grep -qF -- "$2" "$R/CHANGELOG.md"; then bad "$1: found $2"; else ok "$1"; fi; }

echo "== the standard repo, byte for byte"
fresh; expect ok "writes CHANGELOG.md"
cat > "$TMP/want" <<'EOF'
# Changelog

<!-- Generated by .claude/scripts/changelog.py (make changelog) from merged pull requests,
     release tags and docs/releases.toml. Don't edit by hand: spec 08 §Release, decision-022. -->

Every pull request merged into `dev`, by release. Versions are one semver for the backend and the
frontend, tagged `vX.Y.Z` on `main`. A release's Data section names the index it was verified on: the
code version never decides which papers a query matches; `index_version` and `query_version` do.

## Unreleased

### Added

- **Breaking:** drop the v0 route ([#4](https://github.com/o/r/pull/4))

### Changed

- a note from a fork ([#8](https://github.com/o/r/pull/8))
- Tidy the notes ([#11](https://github.com/o/r/pull/11))

### Fixed

- Read the archive\* ([#3](https://github.com/o/r/pull/3))

## 0.1.0

### Added

- an earlier feature ([#10](https://github.com/o/r/pull/10))
- add the lexer ([#1](https://github.com/o/r/pull/1))

### Fixed

- query: keep NEAR \<in\> one \[field\] ([#2](https://github.com/o/r/pull/2))

### Internal

- pin actions ([#9](https://github.com/o/r/pull/9))

### Data

- index_version `0123456789ab`, snapshot `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
- TOKENIZER_VERSION 2 · SCHEMA_VERSION 2 · QUERY_VERSION 2
- First release: no earlier search records.
EOF
if diff -u "$TMP/want" "$R/CHANGELOG.md" > "$TMP/diff"; then ok "matches the golden"; else bad "differs from the golden"; cat "$TMP/diff"; fi
cp "$R/CHANGELOG.md" "$TMP/first"; run
if cmp -s "$TMP/first" "$R/CHANGELOG.md"; then ok "a second run gives the same bytes"; else bad "a second run changed the bytes"; fi
expect ok  "--check on the file it just wrote"                           --check
printf 'x\n' >> "$R/CHANGELOG.md"
expect err "--check on an edited file"                                  --check
rm "$R/CHANGELOG.md"
expect err "--check with no CHANGELOG.md"                               --check
if [ ! -e "$R/CHANGELOG.md" ]; then ok "--check writes nothing"; else bad "--check wrote CHANGELOG.md"; fi

echo "== --release"
fresh; expect err "no data table for the release"                       --release 0.2.0
fresh; data 0.2.0 2 2 2; versions 0.2.0 0.1.9
expect err "frontend version differs"                                   --release 0.2.0
fresh; data 0.2.0 2 2 2; versions 0.1.9 0.2.0
expect err "backend version differs"                                    --release 0.2.0
fresh; data 0.2.0 2 2 2
expect ok  "versions match and a data table exists"                     --release 0.2.0
has   "the untagged PRs are titled 0.2.0"                               "## 0.2.0"
lacks "no Unreleased section"                                           "## Unreleased"
has   "unchanged versions replay reproduced"                            "Search records saved on 0.1.0 replay as \`reproduced\`"
fresh; versions 0.1.0 0.1.0
expect err "a version already tagged"                                   --release 0.1.0
fresh; data 0.0.9 2 2 2; versions 0.0.9 0.0.9
expect err "a version older than the latest tag"                        --release 0.0.9
fresh; data 0.2.0 2 2 2
expect err "not MAJOR.MINOR.PATCH"                                      --release 0.2
fresh; data 0.2.0 2 2 2; "${G[@]}" checkout -q "$C3"
expect ok  "on a HEAD behind dev"                                       --release 0.2.0
if [ "$(sed -n '/^## Unreleased/,/^## 0.2.0/p' "$R/CHANGELOG.md" | grep -c '(\[#\(4\|11\)\]')" = 2 ] \
  && [ "$(sed -n '/^## 0.2.0/,/^## 0.1.0/p' "$R/CHANGELOG.md" | grep -c '(\[#\(3\|8\)\]')" = 2 ]; then
  ok "only the PRs in HEAD are titled 0.2.0; later ones stay Unreleased"; else bad "--release placed PRs outside HEAD"; cat "$R/CHANGELOG.md"; fi
fresh; data 0.2.0 2 2 2; "${G[@]}" tag -a v0.1.1 -m v0.1.1; data 0.1.1 2 2 2
expect err "nothing merged since the last tag"                          --release 0.2.0

echo "== --notes"
fresh; python3 "$R/.claude/scripts/changelog.py" --repo o/r --prs "$TMP/prs.json" --notes 0.1.0 > "$TMP/notes" 2> "$TMP/out"
sed -n '/^## 0.1.0$/,$p' "$TMP/want" | tail -n +3 > "$TMP/want-notes"
if cmp -s "$TMP/want-notes" "$TMP/notes"; then ok "prints the 0.1.0 section without its heading"; else bad "--notes 0.1.0"; diff -u "$TMP/want-notes" "$TMP/notes"; fi
if [ ! -e "$R/CHANGELOG.md" ]; then ok "--notes writes nothing"; else bad "--notes wrote CHANGELOG.md"; fi
expect err "--notes for a release that doesn't exist"                   --notes 0.3.0
data 0.2.0 2 2 2
if python3 "$R/.claude/scripts/changelog.py" --repo o/r --prs "$TMP/prs.json" --release 0.2.0 --notes 0.2.0 > "$TMP/notes" 2> "$TMP/out" \
  && head -3 "$TMP/notes" | grep -qF "**Breaking:** drop the v0 route"; then ok "--release with --notes gives the pending release's notes"; else bad "--release --notes"; cat "$TMP/notes" "$TMP/out"; fi

echo "== replay across versions"
fresh; data 0.1.1 3 2 2; versions 0.1.1 0.1.1
expect err "a TOKENIZER_VERSION change in a patch release"              --release 0.1.1
fresh; data 0.1.1 2 2 3; versions 0.1.1 0.1.1
expect err "a QUERY_VERSION change in a patch release"                  --release 0.1.1
fresh; data 0.1.1 2 3 2; versions 0.1.1 0.1.1
expect err "a SCHEMA_VERSION change in a patch release"                 --release 0.1.1
fresh; data 0.2.0 2 2 3
expect ok  "a QUERY_VERSION change in a minor release"                  --release 0.2.0
has   "called out at the top"                                           "**Search records saved on 0.1.0 replay as \`drifted\`: QUERY_VERSION 2 → 3.**"
if [ "$(grep -A2 '^## 0.2.0' "$R/CHANGELOG.md" | tail -1)" = "**Search records saved on 0.1.0 replay as \`drifted\`: QUERY_VERSION 2 → 3.**" ]; then
  ok "the callout is the section's first line"; else bad "the callout is not the section's first line"; fi
fresh; data 0.1.1 2 2 2; versions 0.1.1 0.1.1
expect ok  "a patch release with unchanged versions"                    --release 0.1.1

echo "== tags and data"
fresh; : > "$R/docs/releases.toml"
expect err "a tagged release with no data table"
fresh; printf '[releases."0.1.0"]\nindex_version = "XYZ"\n' > "$R/docs/releases.toml"
expect err "a data table missing keys"
fresh; sed -i.bak 's/^index_version = .*/index_version = "0123456789AB"/' "$R/docs/releases.toml"
expect err "an index_version that is not 12 lowercase hex"
fresh; sed -i.bak 's/^snapshot_hash = .*/snapshot_hash = "abc"/' "$R/docs/releases.toml"
expect err "a snapshot_hash that is not 64 hex"
fresh; printf 'owner = "x"\n' >> "$R/docs/releases.toml"
expect err "an unknown key in a data table"
fresh; printf 'notes = "   "\n' >> "$R/docs/releases.toml"
expect err "a blank value"
fresh; printf '[other]\n' >> "$R/docs/releases.toml"
expect err "an unknown top-level table"
fresh; printf 'notes = "a new\\n  crawl"\n' >> "$R/docs/releases.toml"
expect ok  "notes are written on one line"
has   "the notes line"                                                  "- a new crawl"
fresh; rm "$R/docs/releases.toml"; "${G[@]}" tag -d v0.1.0 >/dev/null
expect ok  "no tags and no data file: everything is Unreleased"
lacks "no release section"                                              "## 0.1.0"
fresh; sed -i.bak "s/$C3/$(printf 'f%.0s' $(seq 1 40))/" "$TMP/prs.json"
expect err "a merge commit the repo doesn't have"
fresh; "${G[@]}" tag v1.0 >/dev/null; "${G[@]}" tag vnext >/dev/null
expect ok  "tags that aren't vX.Y.Z are ignored"

echo "== PR list"
fresh; sed -i.bak 's/"title":"ci: pin actions"/"title":"ci: pin Co-Authored-By: Claude"/' "$TMP/prs.json"
expect err "an AI-attribution marker in a title"
fresh; sed -i.bak 's/"title":"ci: pin actions"/"title":"ci: noreply@anthropic.com"/' "$TMP/prs.json"
expect err "an attribution address in a title"
fresh; sed -i.bak 's/"number":10,/"number":1,/' "$TMP/prs.json"
expect err "a repeated PR number"
fresh; sed -i.bak "s/$C1\"/${C1:0:12}\"/" "$TMP/prs.json"
expect err "a short merge sha"
fresh; sed -i.bak 's/"base":"dev","head":"feat\/lexer",//' "$TMP/prs.json"
expect err "an entry missing fields"
fresh; printf '{}' > "$TMP/prs.json"
expect err "not a JSON array"
fresh; printf '[' > "$TMP/prs.json"
expect err "not JSON"
fresh; sed -i.bak 's/"head_repo":"fork\/r"/"head_repo":null/' "$TMP/prs.json"
expect ok  "a deleted fork (head_repo null) into main is counted"
has   "the deleted fork's PR"                                           "[#8]"
fresh
if python3 "$R/.claude/scripts/changelog.py" --prs "$TMP/prs.json" > "$TMP/out" 2>&1; then bad "ran without a repo"; else ok "no --repo and no origin remote -> err"; fi
"${G[@]}" remote add origin git@github.com:acme/widgets.git
if python3 "$R/.claude/scripts/changelog.py" --prs "$TMP/prs.json" > "$TMP/out" 2>&1; then ok "origin remote read"; else bad "origin remote read"; cat "$TMP/out"; fi
has   "links name the origin repo"                                      "https://github.com/acme/widgets/pull/1)"

echo "== fetching through gh (a fake gh on PATH)"
fresh; mkdir -p "$TMP/bin"
python3 - "$TMP/prs.json" > "$TMP/lines" <<'PY'
import json, sys
for row in json.load(open(sys.argv[1])):
    print(json.dumps(row))
PY
cat > "$TMP/bin/gh" <<EOF
#!/usr/bin/env bash
printf '%s\n' "\$*" > "$TMP/gh-args"
cat "$TMP/lines"
EOF
chmod +x "$TMP/bin/gh"
cp "$TMP/want" "$TMP/want-gh"
if PATH="$TMP/bin:$PATH" python3 "$R/.claude/scripts/changelog.py" --repo o/r > "$TMP/out" 2>&1 && cmp -s "$TMP/want-gh" "$R/CHANGELOG.md"; then
  ok "gh's JSON lines give the golden"; else bad "gh's JSON lines differ from the golden"; cat "$TMP/out"; fi
if grep -q -- '--paginate' "$TMP/gh-args" && grep -q 'repos/o/r/pulls?state=closed' "$TMP/gh-args"; then ok "asks every page of closed PRs"; else bad "gh args: $(cat "$TMP/gh-args")"; fi
printf '#!/usr/bin/env bash\necho "HTTP 401" >&2\nexit 1\n' > "$TMP/bin/gh"
if PATH="$TMP/bin:$PATH" python3 "$R/.claude/scripts/changelog.py" --repo o/r > "$TMP/out" 2>&1; then bad "a failing gh is not a refusal"; else ok "a failing gh -> err"; fi

echo "passed: $pass  failed: $fail"
[ "$fail" -eq 0 ]
