/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description The served index's coverage, computed and checked when it was loaded (with the engine, one bundle).
         */
        get: operations["get_coverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Every record the query matches, in `format`: of `q` (with `mode`, default `native`) on the pinned
         *     `index_version` (else the served index), or the stored ids of search record `record_id` (alone) from the
         *     index it names. Never paginated or truncated; `X-Total` equals `/search`'s `total` for the same query and
         *     index (for a record, its stored `total`).
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Healthz
         * @description Always 200 while the process serves requests; `index_loaded` is false until the first load succeeds
         *     (search routes answer 503 `API_INDEX_NOT_LOADED` meanwhile).
         */
        get: operations["get_healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paper
         * @description The paper with this id in the served index, as its snapshot holds it (the records loaded with that
         *     very engine: one bundle, whatever swaps happen meanwhile); with `q`, whether that query matches it and
         *     its highlights, as `/search` gives them.
         */
        get: operations["get_paper"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Query
         * @description 02's ParseResult for `q` (debounced as the user types). It reports a parse: any well-formed body is
         *     a 200 whose `errors` say why the query doesn't parse (`PARSE_TOO_LONG` included); only a malformed body
         *     is refused (422 `API_BAD_PARAM`).
         */
        post: operations["parse_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Record
         * @description Freeze a search as an immutable record: re-run here on the served index, then one transaction. With
         *     `index_version`, only if the served index is that one (409 `API_INDEX_VERSION_UNAVAILABLE` otherwise).
         */
        post: operations["create_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record
         * @description The stored record and a replay of it now (HTTP 200 whatever the status). `ids` is null unless
         *     `include=ids`; `/export?record_id=` streams the papers themselves. With `replay=false`, the stored record
         *     alone (`replay` null; the top-level versions are the served index's).
         */
        get: operations["get_record"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record Diff
         * @description The ids a replay now adds and removes, with titles, and which `index_version` inputs changed. Each
         *     list is paged by `offset`/`limit` (≤ 200, never clamped); `added_total`/`removed_total` are in full. A
         *     title comes from the index the replay ran on, null if it doesn't hold the paper. A refused replay
         *     compared nothing: empty lists, null totals.
         */
        get: operations["get_record_diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description One page of the ranked matched set, with its total, exclusion accounting, disjunctive facets and
         *     highlights. `limit` over 200 is a 422 (never clamped); a query that doesn't parse is a 422 with its
         *     diagnostics.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbstractSource */
        AbstractSource: {
            /**
             * Origin
             * @description The site that published the abstract; null when the claim names none this instance knows. `iclr_archive` can't occur yet: the ICLR archive supplies no abstracts (spec 01 §Sources).
             */
            origin: ("openreview" | "neurips_proceedings" | "iclr_proceedings" | "pmlr" | "iclr_archive") | null;
            /**
             * Source
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            source: "openreview_v2" | "openreview_v1" | "iclr_archive" | "neurips_proceedings" | "pmlr" | "ris";
            /** Url */
            url: string | null;
        };
        /** And */
        And: {
            /** Children */
            children: (components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"] | components["schemas"]["Near"] | components["schemas"]["Filter"] | components["schemas"]["Not"] | components["schemas"]["And"] | components["schemas"]["Or"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "and";
            /** Span */
            span: [
                number,
                number
            ];
        };
        /** ChangedInput */
        ChangedInput: {
            current: components["schemas"]["JsonValue"];
            /**
             * Input
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            input: "snapshot_hash" | "tokenizer_version" | "schema_version" | "ranking_params" | "query_version";
            /**
             * Kind
             * @enum {string}
             */
            kind: "corpus" | "method";
            recorded: components["schemas"]["JsonValue"];
        };
        /**
         * Claim
         * @description One source's statement about one field. Frozen and scalar (tuples for lists), so claims are
         *     hashable and set-comparable. `fetched_at` comes from the cache entry, never from build time.
         */
        Claim: {
            /** Evidence */
            evidence: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Field
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            field: "title" | "abstract" | "authors" | "venue" | "year" | "track" | "status" | "presentation" | "venue_id_raw" | "keywords" | "urls.forum" | "urls.pdf" | "urls.proceedings" | "urls.doi";
            /**
             * Source
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            source: "openreview_v2" | "openreview_v1" | "iclr_archive" | "neurips_proceedings" | "pmlr" | "ris";
            /** Url */
            url: string | null;
            value: components["schemas"]["ClaimValue"];
        };
        ClaimValue: string | number | string[] | null;
        /** CoverageCell */
        CoverageCell: {
            /** Count */
            count: number;
            /**
             * Status
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            status: "accepted" | "rejected" | "withdrawn" | "desk_rejected" | "unknown";
            /**
             * Track
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            track: "main" | "datasets_benchmarks" | "position" | "workshop" | "competition" | "tiny_papers" | "blogpost" | "other" | "unknown";
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Index Version */
            index_version: string;
            /** Query Version */
            query_version: string;
            snapshot: components["schemas"]["SnapshotInfo"];
            /** Tokenizer Version */
            tokenizer_version: string;
            totals: components["schemas"]["CoverageTotals"];
            /** Venue Years */
            venue_years: components["schemas"]["VenueYearCoverage"][];
        };
        /** CoverageTotals */
        CoverageTotals: {
            /** Abstract Missing */
            abstract_missing: number;
            /** Records */
            records: number;
            /** Unknown Status */
            unknown_status: number;
            /** Unknown Track */
            unknown_track: number;
        };
        /**
         * CrawlWindow
         * @description When a source (or, under key `*`, the whole corpus) was fetched: the first and the last fetch. The
         *     shape of `crawl_dates` in a search record and in `GET /coverage`'s `snapshot`.
         */
        CrawlWindow: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /**
         * Dedup
         * @description Corpus-wide ingest merges from the snapshot manifest (PRISMA-S item 16): a process statement, never a
         *     removal count of this search. The not-merged counts are the manifest's conflicts by resolution: pairs
         *     that looked alike but were kept apart (two candidates from one source; a track the proceedings never
         *     host; two records of one venue-year). The last two are None on a v1 body, which didn't record them.
         */
        Dedup: {
            /** Ambiguous Not Merged */
            ambiguous_not_merged: number;
            /** Merged */
            merged: number;
            /** Track Not Merged */
            track_not_merged: number | null;
            /** Venue Year Not Merged */
            venue_year_not_merged: number | null;
        };
        /**
         * Diagnostic
         * @description A warning, error or translation notice about a query, with a half-open code-point span into `q`.
         *     `reading` is only ever set on `WARN_MIXED_AND_OR`, so a client never parses `message` for it.
         */
        Diagnostic: {
            code: components["schemas"]["DiagnosticCode"];
            /** Message */
            message: string;
            /**
             * Reading
             * @description Only ever set on `WARN_MIXED_AND_OR`: the text at `span` as it was read, each `AND` group in parentheses and the branches joined with ` OR ` (`a b OR c` → `(a b) OR c`). Replacing `span` in `q` with it gives a query with the same canonical form whose level no longer mixes `AND` and `OR`. Never shortened, unlike the reading quoted in `message`. Null on every other code, and on a `WARN_MIXED_AND_OR` that has none to offer: the "… and N more" summary, or a level where part doesn't parse (its `message` then quotes no reading either).
             */
            reading: string | null;
            /** Span */
            span: [
                number,
                number
            ] | null;
        };
        /**
         * DiagnosticCode
         * @description Open set: new values may be added within /api/v1; handle a value you don't know.
         * @enum {string}
         */
        DiagnosticCode: "PARSE_UNBALANCED_PAREN" | "PARSE_EMPTY_GROUP" | "PARSE_ALL_NEGATIVE" | "PARSE_UNTERMINATED_PHRASE" | "PARSE_BAD_NEAR" | "PARSE_WILDCARD_NOT_SUFFIX" | "PARSE_EXPECTED_TERM" | "PARSE_EMPTY_TERM" | "PARSE_NESTED_FIELD" | "PARSE_TOO_DEEP" | "PARSE_WILDCARD_DETACHED" | "PARSE_AMBIGUOUS_MINUS" | "PARSE_STRAY_COLON" | "PARSE_AMBIGUOUS_QUOTE" | "PARSE_PAREN_TOUCHES_WORD" | "PARSE_TOO_LONG" | "WILDCARD_STEM_TOO_SHORT" | "WILDCARD_TOO_MANY_EXPANSIONS" | "FIELD_UNKNOWN" | "FIELD_UNKNOWN_VALUE" | "FIELD_RANGE_INVERTED" | "FIELD_FILTER_SYNTAX" | "FIELD_COMPAT_ONLY" | "WARN_LOWERCASE_OPERATOR" | "WARN_MIXED_AND_OR" | "WARN_NESTED_FILTER" | "WARN_FILTER_SCOPE" | "WARN_LOOKALIKE_OPERATOR" | "WARN_SYMBOLS_DROPPED" | "WARN_SOURCE_PARTIAL" | "WARN_CJK_RUN" | "WARN_SPELLED_GREEK" | "COMPAT_SOURCE_ALIAS" | "COMPAT_POP_DOLLAR" | "COMPAT_POP_PHRASE" | "COMPAT_NO_STEMMING" | "API_BAD_PARAM" | "API_PAPER_NOT_FOUND" | "API_RECORD_NOT_FOUND" | "API_INDEX_VERSION_UNAVAILABLE" | "API_RECORD_MISMATCH" | "API_RATE_LIMITED" | "API_INDEX_NOT_LOADED" | "API_INTERNAL" | "API_NOT_FOUND" | "API_METHOD_NOT_ALLOWED" | "API_REPLAY_MISMATCH" | "API_RECORDS_STORE_FULL" | "API_BODY_TOO_LARGE" | "API_BUSY" | "API_TOO_MANY_VERIFIED_CLAUSES" | "API_QUERY_TOO_COSTLY";
        /** DiffEntry */
        DiffEntry: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** Diagnostics */
            diagnostics?: components["schemas"]["Diagnostic"][];
            /** Message */
            message: string;
        };
        /**
         * ErrorCode
         * @description An error envelope's code (spec 04 §Error handling). Open set: new values may be added within /api/v1; handle a value you don't know.
         * @enum {string}
         */
        ErrorCode: "PARSE_UNBALANCED_PAREN" | "PARSE_EMPTY_GROUP" | "PARSE_ALL_NEGATIVE" | "PARSE_UNTERMINATED_PHRASE" | "PARSE_BAD_NEAR" | "PARSE_WILDCARD_NOT_SUFFIX" | "PARSE_EXPECTED_TERM" | "PARSE_EMPTY_TERM" | "PARSE_NESTED_FIELD" | "PARSE_TOO_DEEP" | "PARSE_WILDCARD_DETACHED" | "PARSE_AMBIGUOUS_MINUS" | "PARSE_STRAY_COLON" | "PARSE_AMBIGUOUS_QUOTE" | "PARSE_PAREN_TOUCHES_WORD" | "PARSE_TOO_LONG" | "WILDCARD_STEM_TOO_SHORT" | "WILDCARD_TOO_MANY_EXPANSIONS" | "FIELD_UNKNOWN" | "FIELD_UNKNOWN_VALUE" | "FIELD_RANGE_INVERTED" | "FIELD_FILTER_SYNTAX" | "FIELD_COMPAT_ONLY" | "API_BAD_PARAM" | "API_PAPER_NOT_FOUND" | "API_RECORD_NOT_FOUND" | "API_INDEX_VERSION_UNAVAILABLE" | "API_RECORD_MISMATCH" | "API_RATE_LIMITED" | "API_INDEX_NOT_LOADED" | "API_INTERNAL" | "API_NOT_FOUND" | "API_METHOD_NOT_ALLOWED" | "API_RECORDS_STORE_FULL" | "API_BODY_TOO_LARGE" | "API_BUSY" | "API_TOO_MANY_VERIFIED_CLAUSES" | "API_QUERY_TOO_COSTLY";
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * Excluded
         * @description 03's exclusion accounting, verbatim: buckets by count (largest first, ties by name), `unknown` last.
         */
        Excluded: {
            /** Status */
            status: {
                [key: string]: number;
            };
            /** Total */
            total: number;
            /** Track */
            track: {
                [key: string]: number;
            };
        };
        /**
         * Facets
         * @description Disjunctive (decision-001): each field counted without its own top-level conjuncts. Values that
         *     occur only; years as strings.
         */
        Facets: {
            /** Status */
            status: {
                [key: string]: number;
            };
            /** Track */
            track: {
                [key: string]: number;
            };
            /** Venue */
            venue: {
                [key: string]: number;
            };
            /** Year */
            year: {
                [key: string]: number;
            };
        };
        /**
         * Filter
         * @description `field:` restricted to any of `values` (a single-field OR group): YearRanges for `year`, canonical
         *     strings (`vocab.py`) for the others.
         */
        Filter: {
            /**
             * Field
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            field: "venue" | "year" | "track" | "status";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "filter";
            /** Span */
            span: [
                number,
                number
            ];
            /** Values */
            values: (string | components["schemas"]["YearRange"])[];
        };
        /** Health */
        Health: {
            /** Index Loaded */
            index_loaded: boolean;
            /** Index Version */
            index_version: string | null;
            /** Query Version */
            query_version: string;
            /** Tokenizer Version */
            tokenizer_version: string;
        };
        /** Highlights */
        Highlights: {
            /** Abstract */
            abstract: components["schemas"]["Span"][];
            /** Title */
            title: components["schemas"]["Span"][];
        };
        /** Hit */
        Hit: {
            /** Abstract */
            abstract: string | null;
            /** @description Where the hit's `abstract` came from, for attribution (decision-018). `source`: the provenance claim precedence took it from (decision-005), as `GET /papers/{id}` lists it; `ris` means it came through an imported RIS file. `origin`: the site that published it, for a `ris` claim read from the claim's evidence (`scholarmend:openreview_api` → `openreview`, `scholarmend:proceedings_page` → the proceedings its `urls.proceedings` names), null when that names no known site. `url`: the paper's page at `origin` (the OpenReview forum, or the proceedings page; PMLR's CC BY 4.0 terms ask for this link), null when there is none. The whole object is null when `abstract` is null or no claim holds its text. */
            abstract_source: components["schemas"]["AbstractSource"] | null;
            /** Authors */
            authors: string[];
            highlights: components["schemas"]["Highlights"];
            /** Id */
            id: string;
            /** Presentation */
            presentation: ("oral" | "spotlight" | "poster") | null;
            /** Score */
            score: number;
            /**
             * Status
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            status: "accepted" | "rejected" | "withdrawn" | "desk_rejected" | "unknown";
            /** Title */
            title: string;
            /**
             * Track
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            track: "main" | "datasets_benchmarks" | "position" | "workshop" | "competition" | "tiny_papers" | "blogpost" | "other" | "unknown";
            urls: components["schemas"]["Urls"];
            /**
             * Venue
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            venue: "NeurIPS" | "ICLR" | "ICML";
            /** Year */
            year: number;
        };
        JsonValue: unknown;
        /**
         * Limits
         * @description This instance's limits on a query (TASK-089), so a client need not hard-code them: the parser's length
         *     and depth caps, and the served config's verification limits (`op serve` flags; another instance may
         *     differ).
         */
        Limits: {
            /**
             * Max Query Depth
             * @description the deepest nesting of groups and `NOT`s a `q` may have; deeper is 422 `PARSE_TOO_DEEP` (from `/parse`, a 200 whose `errors` hold it)
             */
            max_query_depth: number;
            /**
             * Max Query Length
             * @description the longest `q` in Unicode code points; a longer one, or one whose canonical form is longer, is 422 `PARSE_TOO_LONG` (from `/parse`, a 200 whose `errors` hold it)
             */
            max_query_length: number;
            /**
             * Max Verification Candidates
             * @description the most candidate documents a query's position-verified clauses may read, summed over each clause's fields; more is 422 `API_QUERY_TOO_COSTLY`
             */
            max_verification_candidates: number;
            /**
             * Max Verified Clauses
             * @description the most position-verified clauses a query may have; more is 422 `API_TOO_MANY_VERIFIED_CLAUSES`
             */
            max_verified_clauses: number;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Filter Fields */
            filter_fields: ("venue" | "year" | "track" | "status")[];
            /** Index Version */
            index_version: string;
            /**
             * Index Versions
             * @description every index this instance can serve, sorted, the served one included: an index this code can't open (another tokenizer, schema or Tantivy version) or one currently refused is left out
             */
            index_versions: string[];
            limits: components["schemas"]["Limits"];
            /** Query Version */
            query_version: string;
            /** Text Fields */
            text_fields: ("title" | "abstract")[];
            /** Tokenizer Version */
            tokenizer_version: string;
            values: components["schemas"]["Vocabularies"];
        };
        /**
         * Near
         * @description Both operands within `distance` words of each other, in either order, in one field.
         */
        Near: {
            /** Distance */
            distance: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "near";
            /** Left */
            left: components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"];
            /** Right */
            right: components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"];
            /** Span */
            span: [
                number,
                number
            ];
        };
        /** Not */
        Not: {
            /** Child */
            child: components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"] | components["schemas"]["Near"] | components["schemas"]["Filter"] | components["schemas"]["Not"] | components["schemas"]["And"] | components["schemas"]["Or"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "not";
            /** Span */
            span: [
                number,
                number
            ];
        };
        /** Or */
        Or: {
            /** Children */
            children: (components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"] | components["schemas"]["Near"] | components["schemas"]["Filter"] | components["schemas"]["Not"] | components["schemas"]["And"] | components["schemas"]["Or"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "or";
            /** Span */
            span: [
                number,
                number
            ];
        };
        /** PaperRecord */
        PaperRecord: {
            /** Abstract */
            abstract: string | null;
            /** Authors */
            authors: string[];
            /** Content Hash */
            content_hash: string;
            /** Id */
            id: string;
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /** Presentation */
            presentation: ("oral" | "spotlight" | "poster") | null;
            /**
             * Provenance
             * @default []
             */
            provenance: components["schemas"]["Claim"][];
            /**
             * Status
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            status: "accepted" | "rejected" | "withdrawn" | "desk_rejected" | "unknown";
            /** Title */
            title: string;
            /**
             * Track
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            track: "main" | "datasets_benchmarks" | "position" | "workshop" | "competition" | "tiny_papers" | "blogpost" | "other" | "unknown";
            /** @default {} */
            urls: components["schemas"]["Urls"];
            /**
             * Venue
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            venue: "NeurIPS" | "ICLR" | "ICML";
            /** Venue Id Raw */
            venue_id_raw: string | null;
            /** Year */
            year: number;
        };
        /** PaperResponse */
        PaperResponse: {
            /** @description With `q`: the spans `/search` gives this paper as a hit for that query, over `paper.title` and `paper.abstract` (code points over the raw text); both lists empty when `matched` is false. Null without `q`. */
            highlights: components["schemas"]["Highlights"] | null;
            /** Index Version */
            index_version: string;
            /**
             * Matched
             * @description With `q`: whether the query (default filters included) matches this paper on this index, i.e. whether `/search` would count it in `total`. Null without `q`.
             */
            matched: boolean | null;
            paper: components["schemas"]["PaperRecord"];
            /** Query Version */
            query_version: string;
            /** Tokenizer Version */
            tokenizer_version: string;
        };
        /** ParseRequest */
        ParseRequest: {
            /**
             * Mode
             * @description `native` (this grammar) or `scholar` (Google Scholar / Publish or Perish syntax, translated).
             * @default native
             * @enum {string}
             */
            mode: "native" | "scholar";
            /**
             * Q
             * @description The query (spec 02 grammar). At most 2,000 Unicode code points: a longer one is 422 `PARSE_TOO_LONG`, refused before it is parsed; so is one whose canonical form (defaults written out) is longer, refused after canonicalising.
             */
            q: string;
        };
        /**
         * ParseResponse
         * @description 02's `ParseResult` without `identification_ast` (it stays server-side; spec 04 §Endpoints), plus
         *     `filters` (`query.clauses.filter_clauses`, TASK-078). A query with errors is still a 200 here: `errors`
         *     holds them, and every Optional is null.
         */
        ParseResponse: {
            /** Ast */
            ast: (components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"] | components["schemas"]["Near"] | components["schemas"]["Filter"] | components["schemas"]["Not"] | components["schemas"]["And"] | components["schemas"]["Or"]) | null;
            /** Canonical */
            canonical: string | null;
            /** Canonical Hash */
            canonical_hash: string | null;
            /** Defaults */
            defaults: ("venue" | "year" | "track" | "status")[];
            /** Effective Ast */
            effective_ast: (components["schemas"]["Term"] | components["schemas"]["Wildcard"] | components["schemas"]["Phrase"] | components["schemas"]["Near"] | components["schemas"]["Filter"] | components["schemas"]["Not"] | components["schemas"]["And"] | components["schemas"]["Or"]) | null;
            /** Errors */
            errors: components["schemas"]["Diagnostic"][];
            /** @description Each filter field's top-level clause, for facet and include clicks (spec 02 §Filter clauses; decision-011): its code-point span in `q` and the values it admits, or a zero-width span at the end for an applied default or an unrestricted field; `toggleable` false with a `reason` when a click can't rewrite it. Null exactly when `errors` is non-empty. */
            filters: components["schemas"]["ParsedFilters"] | null;
            /** Identification Query */
            identification_query: string | null;
            /** Index Version */
            index_version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "native" | "scholar";
            /** Query Version */
            query_version: string;
            /** Tokenizer Version */
            tokenizer_version: string;
            /** Translations */
            translations: components["schemas"]["Diagnostic"][];
            /** Warnings */
            warnings: components["schemas"]["Diagnostic"][];
        };
        /**
         * ParsedClause
         * @description A `venue`, `track` or `status` clause.
         */
        ParsedClause: {
            /**
             * Blocking Spans
             * @description For `reason` `multiple_clauses`, `nested` or `mixed_fields`: the clauses behind it, as half-open code-point ranges in `q`, in order: each top-level conjunct (AND groups flattened) that holds a filter of this field, so the UI can point at them. Empty for any other clause (TASK-091).
             */
            blocking_spans: [
                number,
                number
            ][];
            /**
             * Field
             * @description The filter field: always equal to this clause's key in `filters`. Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            field: "venue" | "year" | "track" | "status";
            /**
             * Negated
             * @description The clause is `NOT field:…`. A negated clause is never toggleable.
             */
            negated: boolean;
            /**
             * Reason
             * @description Why it can't be, exactly when `toggleable` is false.
             */
            reason: ("multiple_clauses" | "nested" | "mixed_fields" | "negated" | "too_long" | "too_deep" | "unparsable_edit") | null;
            /**
             * Span
             * @description Half-open code-point range of the clause in `q`. Zero-width at the end, `[len(q), len(q)]`, when the field has no clause of its own (an applied default, or no restriction): a click writes it out as `(q) AND field:(…)`. Null when the field has no single top-level clause (`reason` says why).
             */
            span: [
                number,
                number
            ] | null;
            /**
             * Toggleable
             * @description A facet or include click may rewrite this clause.
             */
            toggleable: boolean;
            /**
             * Values
             * @description The values the clause admits, sorted: an applied default's, or every value for an unrestricted field. Null exactly when `span` is.
             */
            values: string[] | null;
        };
        /**
         * ParsedFilters
         * @description Every filter field's clause (`POST /parse` `filters`).
         */
        ParsedFilters: {
            status: components["schemas"]["ParsedClause"];
            track: components["schemas"]["ParsedClause"];
            venue: components["schemas"]["ParsedClause"];
            year: components["schemas"]["ParsedYearClause"];
        };
        /**
         * ParsedYearClause
         * @description The `year` clause. Years are ranges, not a value list.
         */
        ParsedYearClause: {
            /**
             * Blocking Spans
             * @description For `reason` `multiple_clauses`, `nested` or `mixed_fields`: the clauses behind it, as half-open code-point ranges in `q`, in order: each top-level conjunct (AND groups flattened) that holds a filter of this field, so the UI can point at them. Empty for any other clause (TASK-091).
             */
            blocking_spans: [
                number,
                number
            ][];
            /**
             * Field
             * @description The filter field: always equal to this clause's key in `filters`. Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            field: "venue" | "year" | "track" | "status";
            /**
             * Negated
             * @description The clause is `NOT field:…`. A negated clause is never toggleable.
             */
            negated: boolean;
            /**
             * Ranges
             * @description The year ranges the clause admits, sorted and merged; `1000..9999` for no restriction. Null exactly when `span` is.
             */
            ranges: components["schemas"]["YearRange"][] | null;
            /**
             * Reason
             * @description Why it can't be, exactly when `toggleable` is false.
             */
            reason: ("multiple_clauses" | "nested" | "mixed_fields" | "negated" | "too_long" | "too_deep" | "unparsable_edit") | null;
            /**
             * Span
             * @description Half-open code-point range of the clause in `q`. Zero-width at the end, `[len(q), len(q)]`, when the field has no clause of its own (an applied default, or no restriction): a click writes it out as `(q) AND field:(…)`. Null when the field has no single top-level clause (`reason` says why).
             */
            span: [
                number,
                number
            ] | null;
            /**
             * Toggleable
             * @description A facet or include click may rewrite this clause.
             */
            toggleable: boolean;
        };
        /**
         * Phrase
         * @description Consecutive positions in one field. A wildcard item is expanded at its position (decision-001).
         */
        Phrase: {
            /** Field */
            field: ("title" | "abstract") | null;
            /** Items */
            items: (components["schemas"]["Term"] | components["schemas"]["Wildcard"])[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "phrase";
            /** Span */
            span: [
                number,
                number
            ];
        };
        /** QueryInfo */
        QueryInfo: {
            /** Canonical */
            canonical: string;
            /** Canonical Hash */
            canonical_hash: string;
            /** Expansions */
            expansions: {
                [key: string]: string[];
            };
            /** Identification Query */
            identification_query: string;
            /** Input */
            input: string;
            /** Translations */
            translations: components["schemas"]["Diagnostic"][];
            /** Warnings */
            warnings: components["schemas"]["Diagnostic"][];
        };
        /** RecordCreated */
        RecordCreated: {
            /** Index Version */
            index_version: string;
            /**
             * Page
             * @description The record page's path on the site (`/record/<record_id>`, spec 05), relative to the site's origin. The API resource is the `Location` header (`/api/v1/records/<record_id>`).
             */
            page: string;
            /** Query Version */
            query_version: string;
            /** Record Id */
            record_id: string;
            /** Tokenizer Version */
            tokenizer_version: string;
        };
        /** RecordDiff */
        RecordDiff: {
            /** Added */
            added: components["schemas"]["DiffEntry"][];
            /** Added Total */
            added_total: number | null;
            /** Changed */
            changed: components["schemas"]["ChangedInput"][];
            /** Index Version */
            index_version: string;
            /** Limit */
            limit: number;
            /** Membership Identical */
            membership_identical: boolean | null;
            /** Offset */
            offset: number;
            /** Query Version */
            query_version: string;
            /** Record Id */
            record_id: string;
            /** Recorded Index Version */
            recorded_index_version: string;
            refused: components["schemas"]["DiagnosticCode"] | null;
            /** Removed */
            removed: components["schemas"]["DiffEntry"][];
            /** Removed Total */
            removed_total: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "reproduced" | "drifted" | "mismatch";
            /** Tokenizer Version */
            tokenizer_version: string;
            /** Verified Clauses */
            verified_clauses: number | null;
        };
        /** RecordRequest */
        RecordRequest: {
            /**
             * Index Version
             * @description Optional (TASK-091): the index the search was shown on. The record is saved only if the served index is still that one; otherwise 409 `API_INDEX_VERSION_UNAVAILABLE` and nothing is saved (a hot swap never freezes the query on another index than the one shown). Absent: the served index.
             */
            index_version?: string | null;
            /**
             * Mode
             * @description `native` (this grammar) or `scholar` (Google Scholar / Publish or Perish syntax, translated).
             * @default native
             * @enum {string}
             */
            mode: "native" | "scholar";
            /**
             * Q
             * @description The query (spec 02 grammar). At most 2,000 Unicode code points: a longer one is 422 `PARSE_TOO_LONG`, refused before it is parsed; so is one whose canonical form (defaults written out) is longer, refused after canonicalising.
             */
            q: string;
        };
        /**
         * RecordResponse
         * @description The stored record and a replay of it. With `replay=false` (TASK-091) nothing is replayed: `replay` is
         *     null and the top-level versions are the served index's and this code's.
         */
        RecordResponse: {
            /** Index Version */
            index_version: string;
            /** Query Version */
            query_version: string;
            record: components["schemas"]["SearchRecord"];
            /** @description The replay check (HTTP 200 whatever its status). Null exactly when the request asked `replay=false`; never null otherwise (decision-014). */
            replay: components["schemas"]["ReplayInfo"] | null;
            /** Tokenizer Version */
            tokenizer_version: string;
        };
        /** ReplayInfo */
        ReplayInfo: {
            /** Added Total */
            added_total: number | null;
            /** Changed */
            changed: components["schemas"]["ChangedInput"][];
            excluded: components["schemas"]["Excluded"] | null;
            /** Excluded Match */
            excluded_match: boolean | null;
            /**
             * Identified Total
             * @description The replay's `total` + `excluded.total` (records identified within the query's own limits). Null when `refused`.
             */
            identified_total: number | null;
            /** Ids Hash */
            ids_hash: string | null;
            /** Ids Match */
            ids_match: boolean | null;
            /** Index Version */
            index_version: string;
            /** Membership Identical */
            membership_identical: boolean | null;
            /** Query Version */
            query_version: string;
            refused: components["schemas"]["DiagnosticCode"] | null;
            /** Removed Total */
            removed_total: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "reproduced" | "drifted" | "mismatch";
            /** Total */
            total: number | null;
            /**
             * Unclassified Total
             * @description The replay's `excluded.track.unknown` + `excluded.status.unknown`. Null when `refused`.
             */
            unclassified_total: number | null;
            /** Verified Clauses */
            verified_clauses: number | null;
        };
        /**
         * SearchRecord
         * @description Every field of spec 04 §Search records, plus `body_version`, `schema_version` and `ranking_params`
         *     (the index's other two inputs, so a drifted replay can name a method change after the pinned index is
         *     gone). `ids` is None when the caller didn't ask for them.
         *
         *     Body version 2 adds `sources` (the snapshot manifest's source names, sorted), `identification_citable`
         *     (false when every source is a bootstrap one, `vocab.bootstrap_only`: the corpus is an earlier search's
         *     output, so `total` is not a PRISMA identification number) and `crawl_dates_kind` (per `crawl_dates` key:
         *     `crawl`, `scholar_query_dates` or `mixed`), and `dedup`'s two other not-merged counts. A v1 body has
         *     none of them: they read as None ("not recorded"), never as a guess.
         */
        SearchRecord: {
            /** Body Version */
            body_version: number;
            /** Canonical */
            canonical: string;
            /** Canonical Hash */
            canonical_hash: string;
            /** Crawl Dates */
            crawl_dates: {
                [key: string]: components["schemas"]["CrawlWindow"];
            };
            /**
             * Crawl Dates Kind
             * @description Per `crawl_dates` key, what its window's ends are: `crawl`, `scholar_query_dates` or `mixed` today. Open set: new values may be added within /api/v1; handle a value you don't know.
             */
            crawl_dates_kind: {
                [key: string]: string;
            } | null;
            dedup: components["schemas"]["Dedup"];
            excluded: components["schemas"]["Excluded"];
            /** Expansions */
            expansions: {
                [key: string]: string[];
            };
            /** Identification Citable */
            identification_citable: boolean | null;
            /** Identification Query */
            identification_query: string;
            /**
             * Identified Total
             * @description Records identified within the query's own limits (PRISMA): `total` + `excluded.total`, the count of `identification_query` when the record was saved. The number `op record show` prints as `identified`.
             */
            readonly identified_total: number;
            /** Ids */
            ids: string[] | null;
            /** Ids Hash */
            ids_hash: string;
            /** Index Version */
            index_version: string;
            /** Input */
            input: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "native" | "scholar";
            /** Query Version */
            query_version: string;
            /** Ranking Params */
            ranking_params: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Record Id */
            record_id: string;
            /** Schema Version */
            schema_version: string;
            /**
             * Searched At
             * Format: date-time
             */
            searched_at: string;
            /** Semantic Version */
            semantic_version: string | null;
            /** Snapshot Hash */
            snapshot_hash: string;
            /** Sources */
            sources: string[] | null;
            /** Tokenizer Version */
            tokenizer_version: string;
            /** Total */
            total: number;
            /** Translations */
            translations: components["schemas"]["StoredDiagnostic"][];
            /**
             * Unclassified Total
             * @description Of `excluded.total`, the records removed as unclassified rather than ineligible: `excluded.track.unknown` + `excluded.status.unknown`.
             */
            readonly unclassified_total: number;
            /** Warnings */
            warnings: components["schemas"]["StoredDiagnostic"][];
        };
        /** SearchResponse */
        SearchResponse: {
            excluded: components["schemas"]["Excluded"];
            facets: components["schemas"]["Facets"];
            /** Hits */
            hits: components["schemas"]["Hit"][];
            /**
             * Identified Total
             * @description Records identified within the query's own limits (PRISMA): the count of `identification_query`, i.e. `total` + `excluded.total`. The number `op search` prints as `identified`.
             */
            identified_total: number;
            /** Index Version */
            index_version: string;
            query: components["schemas"]["QueryInfo"];
            /** Query Version */
            query_version: string;
            /** Tokenizer Version */
            tokenizer_version: string;
            /** Total */
            total: number;
            /**
             * Unclassified Total
             * @description Of `excluded.total`, the records removed as unclassified rather than ineligible: `excluded.track.unknown` + `excluded.status.unknown`. The number `op search` prints as `unclassified`.
             */
            unclassified_total: number;
        };
        /**
         * SnapshotInfo
         * @description The snapshot the served index was built from, as its manifest records it.
         */
        SnapshotInfo: {
            /**
             * Built At
             * Format: date-time
             */
            built_at: string;
            /**
             * Crawl Date
             * Format: date
             */
            crawl_date: string;
            /** Crawl Dates */
            crawl_dates: {
                [key: string]: components["schemas"]["CrawlWindow"];
            };
            /**
             * Crawl Dates Kind
             * @description Per `crawl_dates` key, what its window's ends are, derived as a search record's: `crawl` (fetch times, UTC), `scholar_query_dates` (a bootstrap source's window: when its Scholar searches were run) or `mixed` (`*` over both). Open set: new values may be added within /api/v1; handle a value you don't know.
             */
            crawl_dates_kind: {
                [key: string]: string;
            };
            /**
             * Identification Citable
             * @description Whether a search's counts on this snapshot can be cited as PRISMA identification numbers, derived as a search record's: false when every source is a bootstrap one (the corpus is then an earlier search's output, not a database).
             */
            identification_citable: boolean;
            /** Name */
            name: string;
            /** Snapshot Hash */
            snapshot_hash: string;
            /** Sources */
            sources: string[];
        };
        Span: [
            number,
            number
        ];
        /**
         * StoredDiagnostic
         * @description A diagnostic as the record saved it: its code is a string, so a retired code stays readable. `reading`
         *     is null on a record saved before it existed.
         */
        StoredDiagnostic: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Reading
             * @description The diagnostic's `reading` as saved (`WARN_MIXED_AND_OR` only); null on every other code and on a record saved before the field existed.
             */
            reading: string | null;
            /** Span */
            span: [
                number,
                number
            ] | null;
        };
        /** Term */
        Term: {
            /** Field */
            field: ("title" | "abstract") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "term";
            /** Span */
            span: [
                number,
                number
            ];
            /** Token */
            token: string;
        };
        /**
         * TrackCoverage
         * @description One spec 07 §C cell, venue × year × track (TASK-082): what the snapshot indexed for the track, beside
         *     the official accepted count where one is sourced (`official_counts.py`, each with its citation).
         */
        TrackCoverage: {
            /**
             * Abstract Missing
             * @description Of `records`, those without an abstract (title-only).
             */
            abstract_missing: number;
            /**
             * Delta
             * @description `indexed_accepted` − `official_accepted`; null without one.
             */
            delta: number | null;
            /**
             * Delta Pct
             * @description `delta` as a percentage of `official_accepted` (unrounded); null without one.
             */
            delta_pct: number | null;
            /**
             * Gated
             * @description Whether the M4 coverage gate applies: a main-track or D&B cell with an official count.
             */
            gated: boolean;
            /**
             * Indexed Accepted
             * @description Of `records`, those with status `accepted`.
             */
            indexed_accepted: number;
            /**
             * Official Accepted
             * @description The official accepted count for this venue, year and track; null where none is sourced.
             */
            official_accepted: number | null;
            /**
             * Official Accessed
             * @description When `official_citation` was read.
             */
            official_accessed: string | null;
            /**
             * Official Citation
             * @description Where `official_accepted` comes from: a URL or citation.
             */
            official_citation: string | null;
            /**
             * Official Counts
             * @description What `official_accepted` counts (e.g. orals, spotlights and posters, after withdrawals).
             */
            official_counts: string | null;
            /**
             * Records
             * @description Records of this track, every status.
             */
            records: number;
            /**
             * Sources
             * @description The sources the track's records came from (claim sources).
             */
            sources: ("openreview_v2" | "openreview_v1" | "iclr_archive" | "neurips_proceedings" | "pmlr" | "ris")[];
            /**
             * Track
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            track: "main" | "datasets_benchmarks" | "position" | "workshop" | "competition" | "tiny_papers" | "blogpost" | "other" | "unknown";
            /**
             * Within Gate
             * @description For a gated cell, whether |`delta`| is at most 1% of `official_accepted`; null otherwise.
             */
            within_gate: boolean | null;
        };
        /** Urls */
        Urls: {
            /** Doi */
            doi: string | null;
            /** Forum */
            forum: string | null;
            /** Pdf */
            pdf: string | null;
            /** Proceedings */
            proceedings: string | null;
        };
        /**
         * VenueYearCoverage
         * @description One venue-year of the snapshot (`coverage.breakdown`): its cells in vocabulary order (`unknown`
         *     last, never folded), and its unknown and missing-abstract counts, 0 included.
         */
        VenueYearCoverage: {
            /** Abstract Missing */
            abstract_missing: number;
            /** Cells */
            cells: components["schemas"]["CoverageCell"][];
            /** Records */
            records: number;
            /**
             * Statuses Indexed
             * @description The statuses this venue-year's sources can contain at all, in vocabulary order (spec 07 §C): a proceedings-only venue-year lists `accepted` alone, since no rejected paper exists there to exclude. A status can be listed with no record in `cells`.
             */
            statuses_indexed: ("accepted" | "rejected" | "withdrawn" | "desk_rejected" | "unknown")[];
            /**
             * Tracks
             * @description One entry per track with records here, in vocabulary order (`unknown` last).
             */
            tracks: components["schemas"]["TrackCoverage"][];
            /** Unknown Status */
            unknown_status: number;
            /** Unknown Track */
            unknown_track: number;
            /**
             * Venue
             * @description Open set: new values may be added within /api/v1; handle a value you don't know.
             * @enum {string}
             */
            venue: "NeurIPS" | "ICLR" | "ICML";
            /** Year */
            year: number;
        };
        /** Vocabularies */
        Vocabularies: {
            /** Status */
            status: ("accepted" | "rejected" | "withdrawn" | "desk_rejected" | "unknown")[];
            /** Track */
            track: ("main" | "datasets_benchmarks" | "position" | "workshop" | "competition" | "tiny_papers" | "blogpost" | "other" | "unknown")[];
            /** Venue */
            venue: ("NeurIPS" | "ICLR" | "ICML")[];
        };
        /**
         * Wildcard
         * @description A suffix wildcard on one normalised token: `*` is zero or more characters, `$` zero or one.
         */
        Wildcard: {
            /** Field */
            field: ("title" | "abstract") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "wildcard";
            /**
             * Op
             * @enum {string}
             */
            op: "*" | "$";
            /** Span */
            span: [
                number,
                number
            ];
            /** Stem */
            stem: string;
        };
        /** YearRange */
        YearRange: {
            /** Hi */
            hi: number;
            /** Lo */
            lo: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_coverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export: {
        parameters: {
            query: {
                /** @description The file format. */
                format: "ris" | "csv" | "bibtex" | "jsonl";
                /** @description The query (spec 02 grammar). At most 2,000 Unicode code points: a longer one is 422 `PARSE_TOO_LONG`, refused before it is parsed; so is one whose canonical form (defaults written out) is longer, refused after canonicalising. Required unless `record_id` is given. */
                q?: string | null;
                /** @description `native` (this grammar) or `scholar` (Google Scholar / Publish or Perish syntax, translated). With `record_id`, only `native` (a record's canonical string is native syntax); `scholar` there is 422 `API_BAD_PARAM`. */
                mode?: "native" | "scholar";
                /** @description Export from this index (409 `API_INDEX_VERSION_UNAVAILABLE` if this instance can't serve it); the served one if absent. Only with `q`. */
                index_version?: string | null;
                /** @description Export exactly this search record's stored ids, from the index it names. Not with `q` or `index_version`; `mode`, if sent, must be `native`. */
                record_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entire matched set, ordered by id. */
            200: {
                headers: {
                    /** @description attachment; filename="openproceedings-<index_version>-<first 12 of canonical_hash>.<ext>" */
                    "Content-Disposition"?: string;
                    /** @description The index the records were read from */
                    "X-Index-Version"?: string;
                    /** @description This code's query_version (on a `record_id` export too, whatever the record's own) */
                    "X-Query-Version"?: string;
                    /** @description This code's tokenizer_version */
                    "X-Tokenizer-Version"?: string;
                    /** @description How many records the body holds: `/search`'s `total` for the same query and index (for a search record, the number of its stored ids, which its `total` must equal: 409 `API_RECORD_MISMATCH` otherwise) */
                    "X-Total"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/x-bibtex": unknown;
                    "application/x-ndjson": unknown;
                    "application/x-research-info-systems": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_BUSY (with Retry-After): the query needs a slow position check and every verification slot is taken; or API_INDEX_NOT_LOADED (no index loaded yet), or on POST /records API_RECORDS_STORE_FULL (neither sends Retry-After) */
            503: {
                headers: {
                    /** @description Sent with API_BUSY: whole seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_paper: {
        parameters: {
            query?: {
                /** @description Optional: a query (spec 02 grammar) whose highlights to return for this paper, admitted exactly as `/search` admits `q` (at most 2,000 code points, else 422 `PARSE_TOO_LONG`; one that doesn't parse is a 422 with its diagnostics). Without it, `matched` and `highlights` are null. */
                q?: string | null;
                /** @description `native` (this grammar) or `scholar` (Google Scholar / Publish or Perish syntax, translated). Only with `q`: `scholar` without `q` is 422 `API_BAD_PARAM`. */
                mode?: "native" | "scholar";
            };
            header?: never;
            path: {
                /** @description A paper id, `op:<venue>:<year>:<native>`. Any other shape is 422 `API_BAD_PARAM`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperResponse"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_BUSY (with Retry-After): the query needs a slow position check and every verification slot is taken; or API_INDEX_NOT_LOADED (no index loaded yet), or on POST /records API_RECORDS_STORE_FULL (neither sends Retry-After) */
            503: {
                headers: {
                    /** @description Sent with API_BUSY: whole seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    parse_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description The new record's API resource, `/api/v1/records/<id>` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordCreated"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_BUSY (with Retry-After): the query needs a slow position check and every verification slot is taken; or API_INDEX_NOT_LOADED (no index loaded yet), or on POST /records API_RECORDS_STORE_FULL (neither sends Retry-After) */
            503: {
                headers: {
                    /** @description Sent with API_BUSY: whole seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_record: {
        parameters: {
            query?: {
                /** @description `ids` to include the record's sorted id list. */
                include?: "ids" | null;
                /** @description `false` to read the stored record without replaying it (TASK-091): `replay` is then null, nothing is run, so it is answered while verification is busy. Without `include=ids` it costs one token, not the export weight; returning the full membership list costs the export weight. Default `true`: the record and a replay check. */
                replay?: boolean;
            };
            header?: never;
            path: {
                /** @description A search record id: 12 characters of `A-Z a-z 0-9 - _`. Any other shape is 422 `API_BAD_PARAM`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_BUSY (with Retry-After): the query needs a slow position check and every verification slot is taken; or API_INDEX_NOT_LOADED (no index loaded yet), or on POST /records API_RECORDS_STORE_FULL (neither sends Retry-After) */
            503: {
                headers: {
                    /** @description Sent with API_BUSY: whole seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_record_diff: {
        parameters: {
            query?: {
                /** @description Entries of each list (`added`, `removed`) to skip. Past the end is an empty list. */
                offset?: number;
                /** @description Entries of each list per page, 0 to 200. Over 200 is 422 `API_BAD_PARAM`, never clamped. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description A search record id: 12 characters of `A-Z a-z 0-9 - _`. Any other shape is 422 `API_BAD_PARAM`. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDiff"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_BUSY (with Retry-After): the query needs a slow position check and every verification slot is taken; or API_INDEX_NOT_LOADED (no index loaded yet), or on POST /records API_RECORDS_STORE_FULL (neither sends Retry-After) */
            503: {
                headers: {
                    /** @description Sent with API_BUSY: whole seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description The query (spec 02 grammar). At most 2,000 Unicode code points: a longer one is 422 `PARSE_TOO_LONG`, refused before it is parsed; so is one whose canonical form (defaults written out) is longer, refused after canonicalising. */
                q: string;
                /** @description `native` (this grammar) or `scholar` (Google Scholar / Publish or Perish syntax, translated). */
                mode?: "native" | "scholar";
                /** @description The order of `hits`. Never changes `total` or membership (guarantee 5). */
                sort?: "relevance" | "year_desc" | "year_asc" | "title";
                /** @description Hits to skip. Past the end is an empty page, not an error. */
                offset?: number;
                /** @description Hits per page, 0 to 200. Over 200 is 422 `API_BAD_PARAM`, never clamped. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description API_METHOD_NOT_ALLOWED: the endpoint exists, but not for this method */
            405: {
                headers: {
                    /** @description The methods this endpoint takes, comma-separated (RFC 9110 §10.2.1) */
                    Allow?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_RATE_LIMITED: this client's token bucket or its network's (IPv4 /24, IPv6 /48) can't pay for the request, a query's position-verified clauses included; or, on POST /records, the save ceiling of this client's network or of the whole instance is reached */
            429: {
                headers: {
                    /** @description Whole seconds until the request would be allowed */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description API_BUSY (with Retry-After): the query needs a slow position check and every verification slot is taken; or API_INDEX_NOT_LOADED (no index loaded yet), or on POST /records API_RECORDS_STORE_FULL (neither sends Retry-After) */
            503: {
                headers: {
                    /** @description Sent with API_BUSY: whole seconds to wait before retrying */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error (spec 04 §Error handling) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
