// @vitest-environment jsdom
import { cleanup, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createApi } from "@/api/client";
import golden from "@/help/syntax-golden.json";
import defaultLimits from "@/lib/default-limits.json";
import { INITIAL_STATE, searchHref } from "@/lib/search-state";
import { anchorOf, exampleHref, SLOW_CLAUSES_ID, SyntaxHelp, type SyntaxGolden } from "./syntax-help";

// syntax-golden.json is generated by backend/tests/contract/help_golden.py and checked against the parser by
// test_frontend_help_golden.py (which also holds that every reader-facing diagnostic code has an entry).

afterEach(cleanup);

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });
}

const LIMITS = {
  max_query_length: 2000,
  max_query_depth: 64,
  max_verified_clauses: 3,
  max_verification_candidates: 12345,
  max_counted_groups: 4,
  max_counted_terms: 777,
  max_counted_ids: 8888,
};

function page(
  data: SyntaxGolden = golden,
  fetchImpl: typeof fetch = vi
    .fn()
    .mockResolvedValue(json(200, { limits: LIMITS })) as unknown as typeof fetch,
) {
  render(<SyntaxHelp data={data} api={createApi("http://api.test", fetchImpl)} />);
}

/** The text a registry message shows: its backticks become code, the words don't change. */
function shown(message: string): string {
  return message.split("`").join("");
}

describe("Messages (A–Z)", () => {
  it("gives every code its own anchor, the code in lower case, with every example's message verbatim", () => {
    page();
    const codes = [...new Set(golden.messages.map((m) => m.code))];
    for (const code of codes) {
      const section = document.getElementById(anchorOf(code));
      expect(section, code).not.toBeNull();
      expect(within(section!).getByRole("heading", { level: 3 }).textContent).toContain(code);
      for (const m of golden.messages.filter((x) => x.code === code)) {
        expect(section!.textContent).toContain(shown(m.message));
        if (m.example !== null) expect(section!.textContent).toContain(m.example);
        if (m.fix !== null) expect(section!.textContent).toContain(m.fix);
      }
    }
    expect(codes).toEqual([...codes].sort());
  });

  it("points both slow-clause codes at one section", () => {
    page();
    const section = document.getElementById(SLOW_CLAUSES_ID)!;
    for (const code of golden.slow_clauses) {
      const anchor = document.getElementById(anchorOf(code));
      expect(anchor, code).not.toBeNull();
      expect(section.contains(anchor)).toBe(true);
    }
  });

  it("links each fix to a search in the example's own mode", () => {
    page();
    const scholar = golden.messages.find((m) => m.mode === "scholar" && m.fix !== null)!;
    const link = screen.getAllByRole("link", { name: `Search with this example: ${scholar.fix}` })[0]!;
    expect(link.getAttribute("href")).toBe(
      searchHref({ ...INITIAL_STATE, q: scholar.fix!, mode: "scholar" }),
    );
    expect(link.getAttribute("href")).toContain("mode=scholar");
  });

  it("shows a stand-in, and no search link, for an example too long to show", () => {
    page();
    const long = golden.messages.find((m) => m.display !== null)!;
    const section = document.getElementById(anchorOf(long.code))!;
    expect(section.textContent).toContain(long.display);
    expect(section.textContent).not.toContain("x".repeat(100));
  });
});

describe("the sections", () => {
  it("has a contents list whose every link lands on a section", () => {
    page();
    const nav = screen.getByRole("navigation", { name: "On this page" });
    for (const a of within(nav).getAllByRole("link")) {
      const id = a.getAttribute("href")!.slice(1);
      expect(document.getElementById(id), id).not.toBeNull();
    }
  });

  it("shows the golden token rows and spec 02's consequences table", () => {
    page();
    const tokens = screen.getByRole("table", { name: "How text is split into indexed words" });
    const rows = within(tokens).getAllByRole("row").slice(1);
    expect(rows.map((r) => within(r).getByRole("rowheader").textContent)).toEqual(
      golden.tokens.map((t) => t.input),
    );
    rows.forEach((r, i) =>
      expect(r.querySelector("td")!.textContent).toBe(golden.tokens[i]!.tokens.join(", ")),
    );
    const consequences = screen.getByRole("table", { name: "What a query word finds" });
    expect(within(consequences).getAllByRole("row")).toHaveLength(golden.consequences.length + 1);
  });

  it("shows each section example with how it was read and a search link", () => {
    page();
    for (const e of Object.values(golden.sections).flat()) {
      const links = screen.getAllByRole("link", { name: `Search with this example: ${e.q}` });
      expect(links.map((l) => l.getAttribute("href"))).toContain(exampleHref(e.q, e.mode));
      expect(document.body.textContent).toContain(e.canonical);
    }
  });

  it("describes Add $ as an edit of the query that adds at most one character, not Scholar's stemming", () => {
    page();
    const text = document.getElementById("scholar")?.textContent ?? "";
    expect(text).toContain("offers Add $: it writes $ after every listed term that can take one");
    expect(text).toContain("A phrase gets it on its last word.");
    expect(text).toContain(
      `terms with fewer than ${golden.constants.min_wildcard_stem} letters or digits, terms that end in a symbol or have another $ beside them, a lowercase and, or or not, and filter values are left as typed`,
    );
    expect(text).toContain("the notice says so and offers nothing");
    expect(text).toContain("Nothing is searched until you press Search");
    expect(text).toContain("benchmark$ matches benchmark and benchmarks, not benchmarking");
    expect(text).toContain("fewer forms than Google Scholar counts");
  });

  it("gives the full-text figure the diagnostics row's ED-19 sentence points to, with its index and source", () => {
    page();
    const text = document.getElementById("scholar")?.textContent ?? "";
    expect(text).toContain("can come from full text, which $ does not recover");
    expect(text).toContain("index fd13d8d27535 (2026-10-05)");
    expect(text).toContain("1,752 (96.6%) match the string nowhere in their title or abstract");
    expect(text).toContain("docs/results/2026-10-05-scholar-comparison.md");
  });

  it("names the three tools for a lower count than Google Scholar's, in the order to use them", () => {
    page();
    const text = document.getElementById("scholar")?.textContent ?? "";
    const at = [
      "First, Add $",
      "Then, after a search, the group counts",
      "Last, where this instance offers it, Compare with your records",
    ].map((s) => text.indexOf(s));
    expect(at.every((i) => i >= 0)).toBe(true);
    expect([...at].sort((a, b) => a - b)).toEqual(at);
    expect(text).toContain("the group whose removal adds the most papers is the one narrowing the search");
    expect(text).toContain("For what titles and abstracts can explain, three tools can help you find out why");
    expect(text).toContain(
      "First, Add $ matches one more letter or digit on the terms its notice names (benchmark$: benchmarks); it is not Google Scholar's stemming.",
    );
    expect(text).not.toContain("show why");
    expect(text).not.toContain("stemming would have matched");
  });

  it("takes every number and value list from the golden, none written into the page", () => {
    const changed = structuredClone(golden);
    changed.constants.min_wildcard_stem = 7;
    changed.constants.max_expansions = 4321;
    changed.constants.max_near = 77;
    changed.values.venue = ["NeurIPS", "ICLR", "ICML", "COLT"];
    changed.defaults[1]!.canonical = "status:(accepted OR withdrawn)";
    page(changed);
    const text = document.body.textContent ?? "";
    expect(text).toContain("at least 7 letters or digits");
    expect(text).toContain("at most 4,321 different words");
    expect(text).toContain("up to 77");
    expect(text).toContain("COLT");
    expect(text).toContain("status:(accepted OR withdrawn)");
    expect(text).not.toContain("at least 3 letters or digits");
    // the prose of each section that states a limit (its examples may hold any number)
    for (const id of ["wildcards", "near", "limits", SLOW_CLAUSES_ID]) {
      const prose = document.getElementById(id)!.querySelector(id === "limits" ? "ul" : "p")!;
      expect(prose.textContent, id).not.toMatch(/\b(3|200|100)\b/);
    }
  });
});

describe("Limits", () => {
  it("shows this instance's limits from /meta", async () => {
    page();
    const limits = document.getElementById("limits")!;
    expect(await within(limits).findByText(/At most 3 position-verified clauses/)).toBeTruthy();
    expect(limits.textContent).toContain("At most 12,345 candidate documents");
    expect(limits.textContent).not.toContain("couldn't be loaded");
  });

  it("falls back to the defaults, said to be defaults, when /meta fails", async () => {
    page(golden, vi.fn().mockRejectedValue(new TypeError("offline")) as unknown as typeof fetch);
    const limits = document.getElementById("limits")!;
    expect(
      await within(limits).findByText("This instance's limits couldn't be loaded; these are the defaults."),
    ).toBeTruthy();
    const c = golden.constants;
    expect(limits.textContent).toContain(
      `At most ${c.max_verified_clauses.toLocaleString("en-US")} position-verified`,
    );
    expect(limits.textContent).toContain(c.max_verification_candidates.toLocaleString("en-US"));
  });

  it("uses the reducer's default caps, which the backend pins to /meta too", () => {
    expect(golden.constants.max_query_length).toBe(defaultLimits.max_query_length);
    expect(golden.constants.max_query_depth).toBe(defaultLimits.max_query_depth);
  });
});
