#!/usr/bin/env python3
"""Regenerate .claude/learnings/INDEX.md — one line per entry, newest first.

    python3 .claude/scripts/learnings_index.py           # rewrite INDEX.md
    python3 .claude/scripts/learnings_index.py --check   # CI: fail if stale or an entry is malformed

Each entry must be named YYYY-MM-DD-<slug>.md, start with a `# <title>` line, and carry a
`**Key lesson:** <one sentence>` line. The index is what load-learnings.sh shows at every session start,
so the key lesson is the part that has to stand on its own.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DIR = Path(__file__).resolve().parents[1] / "learnings"
NAME = re.compile(r"^(\d{4}-\d{2}-\d{2})-[a-z0-9-]+\.md$")
KEY = re.compile(r"\*\*Key lesson:\*\*\s*(.+)")
HEADER = (
    "# Learnings index\n\n"
    "Generated by `.claude/scripts/learnings_index.py` — do not edit by hand. Newest first.\n"
    "Shown at every session start by `.claude/hooks/load-learnings.sh`.\n\n"
)


def build() -> tuple[str, list[str]]:
    rows, problems = [], []
    for p in sorted(DIR.glob("*.md"), reverse=True):
        if p.name in {"README.md", "_TEMPLATE.md", "INDEX.md"}:
            continue
        m = NAME.match(p.name)
        if not m:
            problems.append(f"{p.name}: name must be YYYY-MM-DD-<lowercase-slug>.md")
            continue
        text = p.read_text(encoding="utf-8")
        title = next((ln[2:].strip() for ln in text.splitlines() if ln.startswith("# ")), None)
        key = KEY.search(text)
        if not title:
            problems.append(f"{p.name}: missing '# <title>' line")
        if not key:
            problems.append(f"{p.name}: missing '**Key lesson:** …' line")
        if title and key:
            rows.append(f"- {m.group(1)} [{title}]({p.name}) — {key.group(1).strip()}")
    body = "\n".join(rows) if rows else "_No entries yet._"
    return HEADER + body + "\n", problems


def main() -> None:
    content, problems = build()
    target = DIR / "INDEX.md"
    if "--check" in sys.argv:
        stale = not target.exists() or target.read_text(encoding="utf-8") != content
        for p in problems:
            print(f"learnings: {p}", file=sys.stderr)
        if stale:
            print("learnings: INDEX.md is stale — run python3 .claude/scripts/learnings_index.py", file=sys.stderr)
        sys.exit(1 if (problems or stale) else 0)
    target.write_text(content, encoding="utf-8")
    for p in problems:
        print(f"warning: {p}", file=sys.stderr)
    print(f"wrote {target} ({content.count(chr(10) + '- ')} entries)")


if __name__ == "__main__":
    main()
