// @vitest-environment jsdom
import { EditorView } from "@codemirror/view";
import { act, cleanup, fireEvent, screen, within } from "@testing-library/react";
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import type { Schemas } from "@/api/client";
import coverageFixture from "@/components/coverage/coverage-fixture.json";
import { SearchWorkspace } from "@/components/search/search-workspace";
import { INITIAL_STATE, type Mode, type SearchState } from "@/lib/search-state";
import {
  json,
  META,
  parsed,
  pass,
  polyfillLayout,
  renderWithApi,
  type Call,
  type Handler,
} from "@/test/api-stub";
import { readGolden } from "./golden";

const nav = vi.hoisted(() => ({ push: vi.fn(), replace: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => nav, usePathname: () => "/search" }));

beforeAll(polyfillLayout);
beforeEach(() => {
  vi.useFakeTimers({ toFake: ["setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date"] });
  nav.push.mockReset();
});
afterEach(() => {
  cleanup();
  vi.useRealTimers();
});

type Diag = Schemas["Diagnostic"];
const GOLDEN = readGolden();

/**
 * `/parse` answers with the server's real `ast` for every query the builder writes in these tests (they are
 * in `builder-read-golden.json`, generated by the backend); an unknown query is a test bug, so it gets a 500.
 */
function api(extra: (q: string, mode: Mode) => Response | null = () => null): Handler {
  return (call: Call) => {
    if (call.path === "/api/v1/meta") return json(META);
    if (call.path === "/api/v1/coverage") return json(coverageFixture);
    if (call.path === "/api/v1/parse") {
      const { q, mode } = call.body as { q: string; mode: Mode };
      const answer = extra(q, mode);
      if (answer !== null) return answer;
      const c = GOLDEN.find((x) => x.q === q && x.mode === mode && x.errors.length === 0);
      if (c === undefined)
        return json({ error: { code: "TEST_UNKNOWN", message: `no golden AST for ${q}` } }, 500);
      return json(parsed(q, { ast: c.ast as Schemas["ParseResponse"]["ast"], mode }));
    }
    return json({ error: { code: "API_NOT_FOUND", message: "no" } }, 404);
  };
}

function setup(
  state: Partial<SearchState> = {},
  handler: Handler = api(),
  expansions: Record<string, string[]> | null = null,
) {
  const r = renderWithApi(
    <SearchWorkspace state={{ ...INITIAL_STATE, ...state }} expansions={expansions} />,
    handler,
  );
  const view = EditorView.findFromDOM(r.container.querySelector(".cm-editor") as HTMLElement);
  if (view === null) throw new Error("no editor");
  const doc = () => view.state.doc.toString();
  const toBuilder = async () => {
    fireEvent.click(screen.getByRole("tab", { name: "Builder" }));
    await pass(10);
  };
  return { ...r, view, doc, toBuilder };
}

const EXAMPLE = '("foundation model" OR LLM) AND (trustworth* OR trust) AND benchmark AND venue:ICLR';

const groups = () => screen.getAllByRole("group", { name: /^Group \d+ of \d+/u });
const chips = (group: HTMLElement) =>
  within(group)
    .getAllByRole("button")
    .filter((b) => b.getAttribute("data-focus")?.startsWith("term:"))
    .map((b) => b.textContent);
const queryText = () => screen.getByText("Query text:").nextElementSibling?.textContent;

/** Type into the focused term box and press a key there. */
async function typeTerm(value: string, key = "Enter") {
  const box = document.activeElement;
  if (!(box instanceof HTMLInputElement)) throw new Error(`no term box focused: ${String(box?.tagName)}`);
  fireEvent.change(box, { target: { value } });
  fireEvent.keyDown(box, { key });
  await pass(10);
}

describe("the Text/Builder tabs", () => {
  it("is a tablist; Text is selected and the builder isn't mounted until chosen", () => {
    setup({ q: "trust" });
    const list = screen.getByRole("tablist", { name: "Query input" });
    const [text, builder] = within(list).getAllByRole("tab");
    expect(text?.getAttribute("aria-selected")).toBe("true");
    expect(builder?.getAttribute("aria-selected")).toBe("false");
    expect(text?.getAttribute("tabindex")).toBe("0");
    expect(builder?.getAttribute("tabindex")).toBe("-1");
    expect(screen.getByRole("tabpanel", { name: "Text" })).toBeTruthy();
    expect(screen.queryByText(/Papers must match every group/u)).toBeNull();
  });

  it("←/→ select the other tab and keep focus on the tabs", async () => {
    setup({ q: "trust" });
    const text = screen.getByRole("tab", { name: "Text" });
    text.focus();
    fireEvent.keyDown(text, { key: "ArrowRight" });
    await pass(10);
    const builder = screen.getByRole("tab", { name: "Builder" });
    expect(builder.getAttribute("aria-selected")).toBe("true");
    expect(document.activeElement).toBe(builder);
    fireEvent.keyDown(builder, { key: "ArrowLeft" });
    await pass(10);
    expect(screen.getByRole("tab", { name: "Text" }).getAttribute("aria-selected")).toBe("true");
  });

  it("Text → Builder → Text without an edit leaves the query byte for byte as typed", async () => {
    const typed = '(  "foundation model"   OR LLM )  trustworth*   venue:iclr';
    const { doc, toBuilder, view } = setup({ q: typed });
    await toBuilder();
    expect(groups()).toHaveLength(2);
    expect(queryText()).toBe(typed);
    fireEvent.click(screen.getByRole("tab", { name: "Text" }));
    await pass(10);
    expect(doc()).toBe(typed);
    expect(view.hasFocus || document.activeElement === view.contentDOM).toBe(true);
    expect(view.state.selection.main.head).toBe(typed.length);
  });
});

describe("the editable builder (design B1)", () => {
  it("shows the groups, their terms as typed, the AND between them, the limits and the query text", async () => {
    const { toBuilder } = setup({ q: EXAMPLE });
    await toBuilder();
    expect(
      screen.getByText("Papers must match every group. Within a group, any term is enough (OR)."),
    ).toBeTruthy();
    const [g1, g2, g3] = groups();
    if (g1 === undefined || g2 === undefined || g3 === undefined) throw new Error("three groups");
    expect(g1.getAttribute("aria-label")).toBe('Group 1 of 3, any of: "foundation model", LLM');
    expect(g2.getAttribute("aria-label")).toBe("Group 2 of 3, any of: trustworth star, trust");
    expect(chips(g1)).toEqual(['"foundation model"', "LLM"]);
    expect(chips(g3)).toEqual(["benchmark"]);
    expect(within(screen.getByRole("tabpanel", { name: "Builder" })).getAllByText("AND")).toHaveLength(2);
    expect(screen.getByText("venue:ICLR")).toBeTruthy();
    expect(screen.getByText("(search first to edit them in Filters, or edit them in Text)")).toBeTruthy();
    expect(queryText()).toBe(EXAMPLE);
  });

  it("moves focus to the first term of group 1 when the tab is chosen", async () => {
    const { toBuilder } = setup({ q: EXAMPLE });
    await toBuilder();
    expect(document.activeElement?.textContent).toBe('"foundation model"');
  });

  it("adds a term: the draft is rewritten, announced, and Search dispatches builderEdit", async () => {
    const { toBuilder, doc } = setup({ q: EXAMPLE });
    await toBuilder();
    const g3 = groups()[2];
    if (g3 === undefined) throw new Error("group 3");
    fireEvent.click(within(g3).getByRole("button", { name: "+ term" }));
    await pass(10);
    expect(document.activeElement?.getAttribute("aria-label") ?? document.activeElement?.id).toBeTruthy();
    expect(screen.getByLabelText("Term in group 3")).toBe(document.activeElement);
    await typeTerm("leaderboard");
    const edited =
      '("foundation model" OR LLM) AND (trustworth* OR trust) AND (benchmark OR leaderboard) AND venue:ICLR';
    expect(doc()).toBe(edited);
    expect(queryText()).toBe(edited);
    expect(screen.getByText("Term leaderboard added to group 3.")).toBeTruthy();
    // Enter opened a new empty term in the same group; leaving it empty writes nothing
    expect(screen.getByLabelText("Term in group 3")).toBe(document.activeElement);
    fireEvent.keyDown(document.activeElement as Element, { key: "Escape" });
    await pass(10);
    expect(nav.push).not.toHaveBeenCalled(); // typing never navigates
    fireEvent.click(screen.getByRole("button", { name: "Search" }));
    expect(nav.push).toHaveBeenCalledWith(
      `/search?${new URLSearchParams({ q: edited, mode: "native" }).toString()}`,
    );
  });

  it("an empty draft is one empty group with one empty term, focused; Search stays enabled", async () => {
    const { toBuilder } = setup();
    await toBuilder();
    expect(groups()).toHaveLength(1);
    expect(screen.getByLabelText("Term in group 1")).toBe(document.activeElement);
    expect(queryText()).toBe("(empty query)");
    const search = screen.getByRole("button", { name: "Search" });
    expect(search.hasAttribute("disabled")).toBe(false);
    expect(search.getAttribute("aria-disabled")).toBeNull();
  });

  it("offers to split a pasted list, by default", async () => {
    const { toBuilder, doc } = setup();
    await toBuilder();
    const box = screen.getByLabelText("Term in group 1");
    fireEvent.change(box, { target: { value: "bias, fairness; equity" } });
    await pass(10);
    expect(screen.getByRole("button", { name: "Split into 3 terms" })).toBeTruthy();
    expect(screen.getByRole("button", { name: "Keep as one phrase" })).toBeTruthy();
    fireEvent.keyDown(box, { key: "Enter" });
    await pass(10);
    expect(doc()).toBe("(bias OR fairness OR equity)");
    expect(chips(groups()[0] as HTMLElement)).toEqual(["bias", "fairness", "equity"]);
  });

  it("writes several words as one phrase and says so on the chip", async () => {
    const { toBuilder, doc } = setup();
    await toBuilder();
    await typeTerm("foundation model", "Tab");
    fireEvent.blur(screen.getByLabelText("Term in group 1"));
    await pass(10);
    expect(doc()).toBe('"foundation model"');
    expect(screen.getByText("searched as one phrase")).toBeTruthy();
  });

  it("edits a chip in place: Enter commits it, Esc on an unedited new term leaves nothing behind", async () => {
    const { toBuilder, doc } = setup({ q: "title:trust" });
    await toBuilder();
    fireEvent.click(screen.getByRole("button", { name: "title:trust" }));
    await pass(10);
    const box = screen.getByLabelText("Term in group 1");
    expect(box).toBe(document.activeElement);
    expect((box as HTMLInputElement).value).toBe("trust"); // the scope stays on the chip's select
    await typeTerm("trust calibration");
    expect(doc()).toBe('title:"trust calibration"');
    fireEvent.keyDown(screen.getByLabelText("Term in group 1"), { key: "Escape" });
    await pass(10);
    expect(doc()).toBe('title:"trust calibration"');
    expect(chips(groups()[0] as HTMLElement)).toEqual(['title:"trust calibration"']);
  });

  it("sets a term's scope from its chip", async () => {
    const { toBuilder, doc } = setup({ q: "trust" });
    await toBuilder();
    fireEvent.change(screen.getByRole("combobox", { name: "Search in:" }), { target: { value: "title" } });
    await pass(10);
    expect(doc()).toBe("title:trust");
    expect(chips(groups()[0] as HTMLElement)).toEqual(["title:trust"]);
  });

  it("removing a term focuses the previous term; Delete on a chip removes it", async () => {
    const { toBuilder, doc } = setup({ q: "(trust OR reliance) AND benchmark" });
    await toBuilder();
    const reliance = screen.getByRole("button", { name: "reliance" });
    reliance.focus();
    fireEvent.keyDown(reliance, { key: "Delete" });
    await pass(10);
    expect(doc()).toBe("trust AND benchmark");
    expect(document.activeElement?.textContent).toBe("trust");
    // the first term of a group: focus goes to its `+ term`
    fireEvent.click(screen.getByRole("button", { name: "Remove term trust" }));
    await pass(10);
    expect(document.activeElement?.textContent).toBe("+ term");
  });

  it("removing a group focuses the previous group's heading and says how many are left", async () => {
    const { toBuilder, doc } = setup({ q: "(trust OR reliance) AND benchmark" });
    await toBuilder();
    const g2 = groups()[1] as HTMLElement;
    fireEvent.click(within(g2).getByRole("button", { name: "Remove group" }));
    await pass(10);
    expect(doc()).toBe("(trust OR reliance)");
    expect(document.activeElement?.tagName).toBe("H3");
    expect(document.activeElement?.textContent).toBe("Group 1 of 1");
    expect(screen.getByText("Group 2 removed. 1 group.")).toBeTruthy();
  });

  it("moves groups with the buttons and with Alt+↑/↓, never by dragging", async () => {
    const { toBuilder, doc } = setup({ q: "(trust OR reliance) AND benchmark" });
    await toBuilder();
    const g1 = groups()[0] as HTMLElement;
    fireEvent.click(within(g1).getByRole("button", { name: "Move group down" }));
    await pass(10);
    expect(doc()).toBe("benchmark AND (trust OR reliance)");
    expect(screen.getByText("Group moved down: now group 2 of 2.")).toBeTruthy();
    const moved = groups()[1] as HTMLElement;
    fireEvent.keyDown(within(moved).getByRole("button", { name: "trust" }), { key: "ArrowUp", altKey: true });
    await pass(10);
    expect(doc()).toBe("(trust OR reliance) AND benchmark");
    expect(screen.queryAllByRole("button").some((b) => b.getAttribute("draggable") === "true")).toBe(false);
  });

  it("adds an Exclude row, written last as NOT", async () => {
    const { toBuilder, doc } = setup({ q: "trust" });
    await toBuilder();
    fireEvent.click(screen.getByRole("button", { name: "+ Leave out terms" }));
    await pass(10);
    expect(screen.getByText("Leave out papers with any of:")).toBeTruthy();
    expect(screen.getByLabelText("Term to leave out")).toBe(document.activeElement);
    await typeTerm("bias");
    expect(doc()).toBe("trust AND NOT bias");
    expect(screen.getByText("Term bias added to the leave-out terms.")).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Remove leave-out terms" }));
    await pass(10);
    expect(doc()).toBe("trust");
    expect(screen.getByText("Leave-out terms removed.")).toBeTruthy();
  });

  it("shows a diagnostic under the term its span hits", async () => {
    const warn: Diag = {
      code: "WARN_SYMBOLS_DROPPED",
      message: "`C++` loses its symbols",
      span: [9, 12],
      reading: null,
    };
    const handler = api((q) =>
      q === "trust OR C++"
        ? json(
            parsed(q, {
              ast: {
                kind: "or",
                span: [0, 12],
                children: [
                  { kind: "term", token: "trust", field: null, span: [0, 5] },
                  { kind: "term", token: "c", field: null, span: [9, 12] },
                ],
              },
              warnings: [warn],
            }),
          )
        : null,
    );
    const { toBuilder } = setup({ q: "trust OR C++" }, handler);
    await toBuilder();
    const chip = screen.getByRole("button", { name: "C++" });
    const describedBy = (chip.getAttribute("aria-describedby") ?? "").split(" ");
    const note = describedBy.map((id) => document.getElementById(id)?.textContent ?? "").join(" ");
    expect(note).toContain("Warning: `C++` loses its symbols");
  });

  it("says so when the server reads the builder's own query differently from its groups", async () => {
    // a server that read `(trust OR reliance)` as `trust AND reliance`: the builder must not stay silent
    const handler = api((q) =>
      q === "(trust OR reliance)"
        ? json(
            parsed(q, {
              ast: {
                kind: "and",
                span: [0, 19],
                children: [
                  { kind: "term", token: "trust", field: null, span: [1, 6] },
                  { kind: "term", token: "reliance", field: null, span: [10, 18] },
                ],
              },
            }),
          )
        : null,
    );
    const { toBuilder } = setup({ q: "trust" }, handler);
    await toBuilder();
    fireEvent.click(screen.getByRole("button", { name: "+ term" }));
    await pass(10);
    await typeTerm("reliance");
    expect(screen.getByRole("alert").textContent).toContain(
      "The server reads the builder's query differently from these groups",
    );
  });

  it("reads main-7-most-updated in Scholar mode, keeping its source: limits as typed", async () => {
    const main7 = GOLDEN.find(
      (c) => c.mode === "scholar" && c.q.includes("PMLR") && c.q.includes("trust"),
    )?.q;
    if (main7 === undefined) throw new Error("main-7 missing from the golden");
    const { toBuilder } = setup({ q: main7, mode: "scholar" });
    await toBuilder();
    expect(groups()).toHaveLength(3);
    expect(screen.getByText(/^\(source:"ICLR" OR/u)).toBeTruthy();
  });
});

describe("the read-only builder (design B2)", () => {
  it("names the first construct that doesn't fit, focuses the notice, and shows it in the text", async () => {
    const { toBuilder, view, doc } = setup({ q: "trust NEAR/5 calibrat*" });
    await toBuilder();
    const heading = screen.getByRole("heading", { name: "This query is too complex for the builder" });
    expect(document.activeElement).toBe(heading);
    expect(heading.parentElement?.textContent).toContain(
      "trust NEAR/5 calibrat* (proximity) doesn't fit groups of alternatives. The builder shows lists of " +
        "terms joined by OR, combined with AND. Your query is unchanged.",
    );
    expect(screen.queryByRole("button", { name: "+ term" })).toBeNull();
    fireEvent.click(screen.getByRole("button", { name: "Show it in the text" }));
    await pass(10);
    expect(screen.getByRole("tab", { name: "Text" }).getAttribute("aria-selected")).toBe("true");
    expect(doc()).toBe("trust NEAR/5 calibrat*");
    const { from, to } = view.state.selection.main;
    expect([from, to]).toEqual([0, 22]);
  });

  it("says a query with errors can't be shown, and never changes it", async () => {
    const handler = api((q) =>
      q === "trust OR"
        ? json(
            parsed(q, {
              ast: null,
              effective_ast: null,
              canonical: null,
              errors: [
                {
                  code: "PARSE_EXPECTED_TERM",
                  message: "Expected a term after OR.",
                  span: [6, 8],
                  reading: null,
                },
              ],
            }),
          )
        : null,
    );
    const { toBuilder, doc } = setup({ q: "trust OR" }, handler);
    await toBuilder();
    expect(screen.getByRole("heading", { name: "The query has errors, so the builder can't show it." })).toBe(
      document.activeElement,
    );
    expect(screen.getByText(/Fix them in Text\. \(1 error\)/u)).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Edit in Text" }));
    await pass(10);
    expect(doc()).toBe("trust OR");
    expect(screen.getByRole("tab", { name: "Text" }).getAttribute("aria-selected")).toBe("true");
  });

  it("says “Reading the query…” only once /parse is slow", async () => {
    let release: (r: Response) => void = () => {};
    const handler = api((q) =>
      q === "trust" ? (new Promise<Response>((resolve) => (release = resolve)) as unknown as Response) : null,
    );
    setup({ q: "trust" }, handler);
    fireEvent.click(screen.getByRole("tab", { name: "Builder" }));
    await pass(100);
    expect(screen.queryByText("Reading the query…")).toBeNull();
    await pass(300);
    expect(screen.getByText("Reading the query…")).toBeTruthy();
    await act(async () => {
      release(json(parsed("trust", { ast: { kind: "term", token: "trust", field: null, span: [0, 5] } })));
      await Promise.resolve();
    });
    await pass(10);
    expect(groups()).toHaveLength(1);
    expect(document.activeElement?.textContent).toBe("trust");
  });
});

/** Every control Tab can reach inside `root`, in document order. */
const tabbable = (root: HTMLElement) =>
  [...root.querySelectorAll<HTMLElement>("button, input, select, textarea, a[href], [tabindex]")].filter(
    (el) => el.getAttribute("tabindex") !== "-1" && !el.hasAttribute("disabled"),
  );

describe("wildcard expansions under each group (TASK-111)", () => {
  const TRUSTWORTH = { "trustworth*": ["trustworth", "trustworthiness", "trustworthy"] };

  it("shows each group's own wildcards' expansions from the last /search, and says them to a screen reader", async () => {
    const { toBuilder } = setup({ q: EXAMPLE }, api(), TRUSTWORTH);
    await toBuilder();
    const [g1, g2, g3] = groups();
    if (g1 === undefined || g2 === undefined || g3 === undefined) throw new Error("three groups");
    const list = within(g2).getByRole("list", { name: "Expansions" });
    expect(list.textContent).toBe(
      "trustworth* → expands to 3 words: trustworth, trustworthiness, trustworthy",
    );
    expect(within(list).getByText("expands to 3 words:", { exact: false }).className).toContain("sr-only");
    expect(within(g1).queryByRole("list", { name: "Expansions" })).toBeNull();
    expect(within(g3).queryByRole("list", { name: "Expansions" })).toBeNull();
  });

  it("shows none before a search, or for a wildcard the last search didn't have", async () => {
    const { toBuilder } = setup({ q: EXAMPLE }, api(), null);
    await toBuilder();
    expect(screen.queryByRole("list", { name: "Expansions" })).toBeNull();
    cleanup();
    const again = setup({ q: EXAMPLE }, api(), { "calibrat*": ["calibrate"] });
    await again.toBuilder();
    expect(screen.queryByRole("list", { name: "Expansions" })).toBeNull();
  });

  it("keeps a group's expansions through an edit to another group, while the server reads the edit", async () => {
    // the edited query's /parse never answers: the unchanged terms keep what the builder knew
    const held = api((q) =>
      q.includes("leaderboard") ? (new Promise<Response>(() => {}) as unknown as Response) : null,
    );
    const { toBuilder } = setup({ q: EXAMPLE }, held, TRUSTWORTH);
    await toBuilder();
    const g3 = groups()[2];
    if (g3 === undefined) throw new Error("group 3");
    fireEvent.click(within(g3).getByRole("button", { name: "+ term" }));
    await pass(10);
    await typeTerm("leaderboard", "Tab");
    fireEvent.blur(document.activeElement as HTMLElement);
    await pass(10);
    expect(queryText()).toContain("(benchmark OR leaderboard)");
    const g2 = groups()[1];
    if (g2 === undefined) throw new Error("group 2");
    expect(within(g2).getByRole("list", { name: "Expansions" }).textContent).toContain("trustworthiness");
  });

  it("drops an edited wildcard's expansions at once, while the server reads the edit", async () => {
    const held = api((q) =>
      q.includes("trustee") ? (new Promise<Response>(() => {}) as unknown as Response) : null,
    );
    const { toBuilder } = setup({ q: EXAMPLE }, held, TRUSTWORTH);
    await toBuilder();
    const g2 = () => groups()[1] as HTMLElement;
    expect(within(g2()).getByRole("list", { name: "Expansions" })).toBeTruthy();
    fireEvent.click(within(g2()).getByRole("button", { name: "trustworth*" }));
    await pass(10);
    await typeTerm("trustee", "Tab");
    fireEvent.blur(document.activeElement as HTMLElement);
    await pass(10);
    expect(queryText()).toContain("(trustee OR trust)");
    expect(within(g2()).queryByRole("list", { name: "Expansions" })).toBeNull();
  });

  it("shows a wildcard added in the builder once the server has read it", async () => {
    // the builder's query with leaderboar* in group 3: the golden leaderboard query's ast, that term a wildcard
    const golden = GOLDEN.find((c) => c.q.includes("(benchmark OR leaderboard)") && c.mode === "native");
    if (golden?.ast == null) throw new Error("no golden leaderboard query");
    const ast = JSON.parse(
      JSON.stringify(golden.ast).replace(
        /"kind":"term","token":"leaderboard","field":null/u,
        '"kind":"wildcard","stem":"leaderboar","op":"*","field":null',
      ),
    ) as Schemas["ParseResponse"]["ast"];
    const written = golden.q.replace("leaderboard", "leaderboar*");
    const handler = api((q) => (q === written ? json(parsed(q, { ast })) : null));
    const { toBuilder } = setup({ q: EXAMPLE }, handler, { "leaderboar*": ["leaderboard", "leaderboards"] });
    await toBuilder();
    const g3 = () => groups()[2] as HTMLElement;
    fireEvent.click(within(g3()).getByRole("button", { name: "+ term" }));
    await pass(10);
    await typeTerm("leaderboar*", "Tab");
    fireEvent.blur(document.activeElement as HTMLElement);
    await pass(10);
    expect(queryText()).toBe(written);
    expect(within(g3()).getByRole("list", { name: "Expansions" }).textContent).toBe(
      "leaderboar* → expands to 2 words: leaderboard, leaderboards",
    );
  });

  it("shows the Exclude row's expansions too, and a wildcard written twice once", async () => {
    const q = '("x" OR model$ OR model$) -title:(“vision language” | “vision language” | gpt-4*)';
    const { toBuilder } = setup({ q }, api(), { "4*": ["4", "4o"], model$: ["model", "models"] });
    await toBuilder();
    const g1 = groups()[0] as HTMLElement;
    expect(
      within(within(g1).getByRole("list", { name: "Expansions" })).getAllByRole("listitem"),
    ).toHaveLength(1);
    const exclude = screen.getByRole("group", { name: /^Leave out papers with any of:/u });
    expect(within(exclude).getByRole("list", { name: "Expansions" }).textContent).toBe(
      "4* → expands to 2 words: 4, 4o",
    );
  });

  it("puts a long list's rest behind a +N more button the keyboard reaches", async () => {
    const many = Array.from({ length: 11 }, (_, i) => `trustworth${String.fromCharCode(97 + i)}`);
    const { toBuilder } = setup({ q: EXAMPLE }, api(), { "trustworth*": many });
    await toBuilder();
    const g2 = groups()[1];
    if (g2 === undefined) throw new Error("group 2");
    const more = within(g2).getByRole("button", { name: "+3 more" });
    expect(tabbable(g2)).toContain(more);
    expect(more.getAttribute("aria-expanded")).toBe("false");
    fireEvent.click(more);
    expect(within(g2).getByRole("button", { name: "Show fewer" }).getAttribute("aria-expanded")).toBe("true");
    expect(within(g2).getByRole("list", { name: "Expansions" }).textContent).toContain("trustworthk");
  });
});

describe("the parts that fit, under the read-only notice (design B2, TASK-111)", () => {
  const PARTLY = '("x" | abstract:calibrat*) (venue:ICLR OR venue:ICML) trust NEAR/3 bias';

  it("shows the groups and limits that fit, dimmed and without a single control, and focuses the notice", async () => {
    const { toBuilder, doc } = setup({ q: PARTLY }, api(), { "calibrat*": ["calibrate", "calibration"] });
    await toBuilder();
    expect(document.activeElement).toBe(
      screen.getByRole("heading", { name: "This query is too complex for the builder" }),
    );
    const parts = screen.getByRole("region", { name: "Parts that fit the builder" });
    expect(parts.className).toContain("text-muted-foreground");
    expect(parts.textContent).toContain("Anything that doesn't fit is left out. Nothing here can be edited.");
    const [g1, ...rest] = within(parts).getAllByRole("group");
    expect(rest).toHaveLength(0);
    expect(g1?.getAttribute("aria-label")).toBe('Group 1, any of: "x", abstract:calibrat star');
    expect(within(parts).getByText("(venue:ICLR OR venue:ICML)").tagName).toBe("CODE");
    expect(parts.textContent).not.toContain("NEAR");
    // not editable: nothing to press, type in or choose
    expect(tabbable(parts)).toEqual([]);
    expect(within(parts).queryByRole("textbox")).toBeNull();
    expect(within(parts).queryByRole("combobox")).toBeNull();
    expect(within(g1 as HTMLElement).getByRole("list", { name: "Expansions" }).textContent).toContain(
      "calibration",
    );
    // the panel's Tab order is the notice's two buttons only
    const panel = screen.getByRole("tabpanel", { name: "Builder" });
    expect(tabbable(panel).map((b) => b.textContent)).toEqual(["Edit in Text", "Show it in the text"]);
    expect(doc()).toBe(PARTLY);
  });

  it("keeps a long expansion's +N more, the only button among the parts that fit", async () => {
    const many = Array.from({ length: 10 }, (_, i) => `calibrat${String.fromCharCode(97 + i)}`);
    const { toBuilder } = setup({ q: PARTLY }, api(), { "calibrat*": many });
    await toBuilder();
    const parts = screen.getByRole("region", { name: "Parts that fit the builder" });
    const more = within(parts).getByRole("button", { name: "+2 more" });
    expect(tabbable(parts)).toEqual([more]);
    expect(more.className).toContain("text-foreground");
    const panel = screen.getByRole("tabpanel", { name: "Builder" });
    expect(tabbable(panel).map((b) => b.textContent)).toEqual([
      "Edit in Text",
      "Show it in the text",
      "+2 more",
    ]);
  });

  it("keeps the first NOT as the Exclude row and names the second one", async () => {
    const { toBuilder } = setup({ q: "trust NOT a NOT b" });
    await toBuilder();
    expect(screen.getByText(/\(a second NOT\) doesn't fit/u)).toBeTruthy();
    const parts = screen.getByRole("region", { name: "Parts that fit the builder" });
    expect(
      within(parts)
        .getAllByRole("group")
        .map((g) => g.getAttribute("aria-label")),
    ).toEqual(["Group 1, any of: trust", "Leave out papers with any of: a"]);
    expect(parts.textContent).toContain("AND NOT");
  });

  it("shows an Exclude row with no group above it without AND NOT", async () => {
    const q = "(a NEAR/2 b) NOT c";
    const term = (token: string, at: number) => ({
      kind: "term" as const,
      token,
      field: null,
      span: [at, at + 1] as [number, number],
    });
    const ast: Schemas["ParseResponse"]["ast"] = {
      kind: "and",
      span: [0, 18],
      children: [
        { kind: "near", distance: 2, span: [1, 11], left: term("a", 1), right: term("b", 10) },
        { kind: "not", span: [13, 18], child: term("c", 17) },
      ],
    };
    const { toBuilder } = setup(
      { q },
      api((x) => (x === q ? json(parsed(q, { ast })) : null)),
    );
    await toBuilder();
    const parts = screen.getByRole("region", { name: "Parts that fit the builder" });
    expect(
      within(parts)
        .getAllByRole("group")
        .map((g) => g.getAttribute("aria-label")),
    ).toEqual(["Leave out papers with any of: c"]);
    expect(parts.textContent).not.toContain("AND NOT");
  });

  it("shows nothing under the notice when no part fits", async () => {
    const { toBuilder } = setup({ q: "trust NEAR/5 calibrat*" });
    await toBuilder();
    expect(screen.queryByRole("region", { name: "Parts that fit the builder" })).toBeNull();
    expect(screen.queryByRole("group")).toBeNull();
  });
});
