/**
 * The builder goldens, for tests only (`read.test.ts`, `write.test.ts`). The read golden is generated by
 * `backend/tests/contract/test_frontend_builder_golden.py` (the server's `ast` of each query and the
 * backend's reference reading); it is read from disk rather than imported so the type checker never infers a
 * type for a 300 KB literal.
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import type { Mode } from "@/lib/search-state";
import type { AstNode, BlockerKind } from "./model";

type Span = [number, number];

export interface ReadCase {
  readonly q: string;
  readonly mode: Mode;
  readonly errors: readonly string[];
  readonly ast: AstNode | null;
  readonly read:
    | {
        readonly groups: Span[][];
        readonly exclude: Span[] | null;
        readonly exclude_at: number;
        readonly limits: Span[];
      }
    | { readonly blocker: { readonly kind: BlockerKind; readonly span: Span } }
    | null;
}

export const WRITE_GOLDEN_PATH = path.join(import.meta.dirname, "builder-write-golden.json");

export function readGolden(): ReadCase[] {
  const raw: unknown = JSON.parse(
    readFileSync(path.join(import.meta.dirname, "builder-read-golden.json"), "utf8"),
  );
  return (raw as { cases: ReadCase[] }).cases;
}
