// @vitest-environment jsdom
import { cleanup, fireEvent, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Schemas } from "@/api/client";
import type { Mode } from "@/lib/search-state";
import { json, parsed, pass, renderWithApi, type Call } from "@/test/api-stub";
import { ConceptBuilder } from "./concept-builder";
import { readGolden } from "./golden";
import { countsFor, groupTotals, type GroupCounts, type SearchedGroups } from "./group-counts";
import type { AstNode, BuilderGroup, CodePoints } from "./model";
import { spanOf } from "./read";

beforeEach(() => {
  vi.useFakeTimers({ toFake: ["setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date"] });
});
afterEach(() => {
  cleanup();
  vi.useRealTimers();
});

const GOLDEN = readGolden();
const EXAMPLE = '("foundation model" OR LLM) AND (trustworth* OR trust) AND benchmark AND venue:ICLR';
const PARTLY = '("x" | abstract:calibrat*) (venue:ICLR OR venue:ICML) trust NEAR/3 bias';

/** The server's `ast` of a golden query (generated by the backend). */
function astOf(q: string, mode: Mode = "native"): AstNode {
  const ast = GOLDEN.find((c) => c.q === q && c.mode === mode)?.ast;
  if (ast == null) throw new Error(`no golden AST for ${q}`);
  return ast;
}

/**
 * `/search`'s `groups` for a golden query: the server's groups are its top-level AND conjuncts that search
 * text and aren't negated, each at its node's span (`backend/tests/contract/test_group_counts.py` holds the
 * API to that on every golden query), here with the given totals in query order.
 */
function counted(q: string, totals: readonly number[], mode: Mode = "native"): GroupCounts {
  const ast = astOf(q, mode);
  const onlyFilters = (n: AstNode): boolean =>
    n.kind === "filter" || (n.kind === "or" && n.children.every(onlyFilters));
  const groups = (ast.kind === "and" ? ast.children : [ast]).filter(
    (n) => n.kind !== "not" && !onlyFilters(n),
  );
  if (groups.length !== totals.length) throw new Error(`${q} has ${groups.length} groups`);
  return {
    counts: groups.map((n, i) => ({ span: [...spanOf(n)], total: totals[i] ?? 0 })),
    groups_total: groups.length,
    limit: 10,
    not_counted: null,
  };
}

function show(text: string, searched: SearchedGroups | null, mode: Mode = "native") {
  const onEdit = vi.fn<(text: string) => void>();
  const handler = (call: Call) => {
    if (call.path !== "/api/v1/parse") return json({ error: { code: "API_NOT_FOUND", message: "no" } }, 404);
    const { q } = call.body as { q: string };
    const c = GOLDEN.find((x) => x.q === q && x.mode === mode && x.errors.length === 0);
    if (c === undefined) return new Promise<Response>(() => {}); // an edit's parse: never answered here
    return json(parsed(q, { ast: c.ast as Schemas["ParseResponse"]["ast"], mode }));
  };
  const r = renderWithApi(
    <ConceptBuilder
      text={text}
      mode={mode}
      onEdit={onEdit}
      onEditInText={() => {}}
      focusOnOpen={false}
      onFocused={() => {}}
      searched={searched}
    />,
    handler,
  );
  return { ...r, onEdit };
}

const groups = () => screen.getAllByRole("group", { name: /^Group \d+/u });
const NOTE = /the whole query\. A group's count is the papers that match it with the other groups removed/u;

describe("groupTotals", () => {
  const group = (id: number, ...terms: number[]): BuilderGroup => ({
    id,
    terms: terms.map((t) => ({ id: t, text: "x", scope: "any", phrased: false })),
  });
  const spans = new Map<number, CodePoints>([
    [1, [1, 19]],
    [2, [23, 26]],
    [3, [33, 44]],
    [4, [59, 68]],
  ]);
  const counts: GroupCounts["counts"] = [
    { span: [0, 27], total: 6343 },
    { span: [32, 55], total: 529 },
  ];

  it("gives a group the count of the span that holds its terms", () => {
    expect([...groupTotals(counts, [group(10, 1, 2), group(11, 3)], spans)]).toEqual([
      [10, 6343],
      [11, 529],
    ]);
  });

  it("gives a group of one repeated term the count at the first one's span (the canonical form)", () => {
    const repeated: GroupCounts["counts"] = [{ span: [1, 19], total: 40 }];
    expect([...groupTotals(repeated, [group(10, 1, 2)], spans)]).toEqual([[10, 40]]);
  });

  it("gives none to a group the server didn't count, or one with no place in the query", () => {
    const totals = groupTotals(counts, [group(10, 4), group(12, 99), group(13)], spans);
    expect(totals.size).toBe(0);
  });

  it("applies a search's counts only to the draft it searched", () => {
    const searched: SearchedGroups = {
      q: "a b",
      mode: "native",
      total: 1,
      groups: counted(EXAMPLE, [1, 2, 3]),
    };
    expect(countsFor(searched, "a b", "native")).toBe(searched);
    expect(countsFor(searched, "a b ", "native")).toBeNull();
    expect(countsFor(searched, "a b", "scholar")).toBeNull();
    expect(countsFor(null, "a b", "native")).toBeNull();
  });
});

describe("each group's count after a search (TASK-176)", () => {
  const SEARCHED: SearchedGroups = {
    q: EXAMPLE,
    mode: "native",
    total: 67,
    groups: counted(EXAMPLE, [6343, 529, 1]),
  };

  it("shows each group's count as the API sent it, beside the search's total, as plain text", async () => {
    show(EXAMPLE, SEARCHED);
    await pass(10);
    const [g1, g2, g3] = groups();
    if (g1 === undefined || g2 === undefined || g3 === undefined) throw new Error("three groups");
    expect(within(g1).getByText(/this group alone/u).textContent).toBe("6,343 papers match this group alone");
    expect(within(g2).getByText(/this group alone/u).textContent).toBe("529 papers match this group alone");
    expect(within(g3).getByText(/this group alone/u).textContent).toBe("1 paper matches this group alone");
    const note = screen.getByText(NOTE);
    expect(note.textContent).toBe(
      "67 papers match the whole query. A group's count is the papers that match it with the other groups " +
        "removed: the query's limits, leave-out terms and default filters still apply.",
    );
    // the count is content of its group, so a screen reader meets it there; the group keeps its name
    expect(g2.getAttribute("aria-label")).toBe("Group 2 of 3, any of: trustworth star, trust");
  });

  it("shows none before a search", async () => {
    show(EXAMPLE, null);
    await pass(10);
    expect(groups()).toHaveLength(3);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(NOTE)).toBeNull();
  });

  it("shows none for a draft that is not the searched query: its text, or its mode", async () => {
    show(EXAMPLE, { ...SEARCHED, q: `${EXAMPLE} ` });
    await pass(10);
    expect(groups()).toHaveLength(3);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    cleanup();
    show(EXAMPLE, { ...SEARCHED, mode: "scholar" });
    await pass(10);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(NOTE)).toBeNull();
  });

  it("drops every count at once when a builder edit changes the draft", async () => {
    const { onEdit, rerender } = show(EXAMPLE, SEARCHED);
    await pass(10);
    expect(screen.getAllByText(/this group alone/u)).toHaveLength(3);
    fireEvent.click(screen.getAllByRole("button", { name: "Remove group" })[2] as HTMLElement);
    await pass(10);
    const edited = onEdit.mock.calls[0]?.[0];
    if (edited === undefined || edited === EXAMPLE) throw new Error("the edit rewrote the draft");
    rerender(
      <ConceptBuilder
        text={edited}
        mode="native"
        onEdit={onEdit}
        onEditInText={() => {}}
        focusOnOpen={false}
        onFocused={() => {}}
        searched={SEARCHED}
      />,
    );
    await pass(10);
    expect(groups()).toHaveLength(2);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(NOTE)).toBeNull();
  });

  it("shows none for a query that is not an AND of groups", async () => {
    const one: SearchedGroups = {
      q: "trust",
      mode: "native",
      total: 412,
      groups: { counts: [], groups_total: 1, limit: 10, not_counted: "fewer_than_two_groups" },
    };
    show("trust", one);
    await pass(10);
    expect(groups()).toHaveLength(1);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(/whole query|aren't shown/u)).toBeNull();
  });

  it("says why a query of more groups than the site counts has none", async () => {
    const over: SearchedGroups = {
      q: EXAMPLE,
      mode: "native",
      total: 67,
      groups: { counts: [], groups_total: 3, limit: 2, not_counted: "too_many_groups" },
    };
    show(EXAMPLE, over);
    await pass(10);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.getByText(/Group counts aren't shown/u).textContent).toBe(
      "Group counts aren't shown: this query has 3 groups, and this site counts at most 2.",
    );
  });

  it("shows the count of each part that fits under the read-only notice", async () => {
    const searched: SearchedGroups = {
      q: PARTLY,
      mode: "native",
      total: 3,
      groups: counted(PARTLY, [40, 12]),
    };
    show(PARTLY, searched);
    await pass(10);
    const parts = screen.getByRole("region", { name: "Parts that fit the builder" });
    const [g1, ...rest] = within(parts).getAllByRole("group");
    expect(rest).toHaveLength(0);
    expect(within(g1 as HTMLElement).getByText(/this group alone/u).textContent).toBe(
      "40 papers match this group alone",
    );
    expect(within(parts).getByText(NOTE).textContent).toContain("3 papers match the whole query.");
    expect(parts.textContent).not.toContain("12 papers");
  });
});
