// @vitest-environment jsdom
import { cleanup, fireEvent, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Schemas } from "@/api/client";
import type { Mode } from "@/lib/search-state";
import { json, parsed, pass, renderWithApi, type Call } from "@/test/api-stub";
import { ConceptBuilder } from "./concept-builder";
import { readGolden } from "./golden";
import { countsFor, groupTotals, type GroupCounts, type SearchedGroups } from "./group-counts";
import type { AstNode, BuilderGroup, CodePoints } from "./model";
import { spanOf } from "./read";

beforeEach(() => {
  vi.useFakeTimers({ toFake: ["setTimeout", "clearTimeout", "setInterval", "clearInterval", "Date"] });
});
afterEach(() => {
  cleanup();
  vi.useRealTimers();
});

const GOLDEN = readGolden();
const EXAMPLE = '("foundation model" OR LLM) AND (trustworth* OR trust) AND benchmark AND venue:ICLR';
const PARTLY = '("x" | abstract:calibrat*) (venue:ICLR OR venue:ICML) trust NEAR/3 bias';

/** The server's `ast` of a golden query (generated by the backend). */
function astOf(q: string, mode: Mode = "native"): AstNode {
  const ast = GOLDEN.find((c) => c.q === q && c.mode === mode)?.ast;
  if (ast == null) throw new Error(`no golden AST for ${q}`);
  return ast;
}

/**
 * `/search`'s `groups` for a golden query: the server's groups are its top-level AND conjuncts that search
 * text and aren't negated, each at its node's span (`backend/tests/contract/test_group_counts.py` holds the
 * API to that on every golden query), here with the given `[alone, without]` totals in query order.
 */
function counted(
  q: string,
  totals: readonly (readonly [number, number])[],
  mode: Mode = "native",
): GroupCounts {
  const ast = astOf(q, mode);
  const onlyFilters = (n: AstNode): boolean =>
    n.kind === "filter" || (n.kind === "or" && n.children.every(onlyFilters));
  const groups = (ast.kind === "and" ? ast.children : [ast]).filter(
    (n) => n.kind !== "not" && !onlyFilters(n),
  );
  if (groups.length !== totals.length) throw new Error(`${q} has ${groups.length} groups`);
  return {
    counts: groups.map((n, i) => ({
      span: [...spanOf(n)],
      total: totals[i]?.[0] ?? 0,
      total_without: totals[i]?.[1] ?? 0,
    })),
    groups_total: groups.length,
    limit: 10,
    not_counted: null,
  };
}

function show(text: string, searched: SearchedGroups | null, mode: Mode = "native") {
  const onEdit = vi.fn<(text: string) => void>();
  const handler = (call: Call) => {
    if (call.path !== "/api/v1/parse") return json({ error: { code: "API_NOT_FOUND", message: "no" } }, 404);
    const { q } = call.body as { q: string };
    const c = GOLDEN.find((x) => x.q === q && x.mode === mode && x.errors.length === 0);
    if (c === undefined) return new Promise<Response>(() => {}); // an edit's parse: never answered here
    return json(parsed(q, { ast: c.ast as Schemas["ParseResponse"]["ast"], mode }));
  };
  const r = renderWithApi(
    <ConceptBuilder
      text={text}
      mode={mode}
      onEdit={onEdit}
      onEditInText={() => {}}
      focusOnOpen={false}
      onFocused={() => {}}
      searched={searched}
    />,
    handler,
  );
  return { ...r, onEdit };
}

const groups = () => screen.getAllByRole("group", { name: /^Group \d+/u });
const NOTE = /the whole query\. Each group shows how many papers match it with the other groups removed/u;

describe("groupTotals", () => {
  const group = (id: number, ...terms: number[]): BuilderGroup => ({
    id,
    terms: terms.map((t) => ({ id: t, text: "x", scope: "any", phrased: false })),
  });
  const spans = new Map<number, CodePoints>([
    [1, [1, 19]],
    [2, [23, 26]],
    [3, [33, 44]],
    [4, [59, 68]],
  ]);
  const counts: GroupCounts["counts"] = [
    { span: [0, 27], total: 6343, total_without: 139 },
    { span: [32, 55], total: 529, total_without: 2337 },
  ];

  it("gives a group the count of the span that holds its terms", () => {
    expect([...groupTotals(counts, [group(10, 1, 2), group(11, 3)], spans)]).toEqual([
      [10, { kind: "counted", total: 6343, totalWithout: 139 }],
      [11, { kind: "counted", total: 529, totalWithout: 2337 }],
    ]);
  });

  it("gives a group of one repeated term the count at the first one's span (the canonical form)", () => {
    const repeated: GroupCounts["counts"] = [{ span: [1, 19], total: 40, total_without: 90 }];
    expect([...groupTotals(repeated, [group(10, 1, 2)], spans)]).toEqual([
      [10, { kind: "counted", total: 40, totalWithout: 90 }],
    ]);
  });

  it("says a group that means what an earlier counted one means is the same group, by the server's reading", () => {
    // typed differently (`ＬＬＭ` full-width, `llm`), read alike: the server's `ast` holds one token for both
    const leaf = (token: string, span: [number, number]): AstNode => ({
      kind: "term",
      field: null,
      token,
      span,
    });
    const ast: AstNode = {
      kind: "and",
      span: [0, 68],
      children: [
        leaf("llm", [1, 19]),
        leaf("llm", [59, 68]),
        { kind: "or", span: [20, 55], children: [leaf("llm", [23, 26]), leaf("llm", [33, 44])] },
        leaf("other", [70, 75]),
      ],
    };
    const named = (id: number, ...terms: number[]): BuilderGroup => ({
      id,
      terms: terms.map((t) => ({ id: t, text: `typed ${t}`, scope: "any", phrased: false })),
    });
    const more = new Map<number, CodePoints>([...spans, [5, [70, 75]]]);
    const one: GroupCounts["counts"] = [{ span: [0, 27], total: 6343, total_without: 139 }];
    const shown = groupTotals(
      one,
      [named(10, 1), named(11, 4), named(12, 2, 3), named(13, 5), named(14, 99)],
      more,
      ast,
    );
    expect([...shown]).toEqual([
      [10, { kind: "counted", total: 6343, totalWithout: 139 }],
      [11, { kind: "same", as: 1 }], // not counted, and the same token
      // (group 12's first term lies in the counted span: counted, as a repeated-term group is)
      [12, { kind: "counted", total: 6343, totalWithout: 139 }],
      // 13 means something else; 14 has no place in the query: nothing
    ]);
    // without the server's reading nothing is called the same: typed text is never compared
    expect([...groupTotals(one, [named(10, 1), named(11, 4)], more)]).toEqual([
      [10, { kind: "counted", total: 6343, totalWithout: 139 }],
    ]);
  });

  it("gives none to a group the server didn't count, or one with no place in the query", () => {
    const totals = groupTotals(counts, [group(10, 4), group(12, 99), group(13)], spans);
    expect(totals.size).toBe(0);
  });

  it("applies a search's counts only to the draft it searched", () => {
    const searched: SearchedGroups = {
      q: "a b",
      mode: "native",
      total: 1,
      groups: counted(EXAMPLE, [
        [1, 9],
        [2, 9],
        [3, 9],
      ]),
    };
    expect(countsFor(searched, "a b", "native")).toBe(searched);
    expect(countsFor(searched, "a b ", "native")).toBeNull();
    expect(countsFor(searched, "a b", "scholar")).toBeNull();
    expect(countsFor(null, "a b", "native")).toBeNull();
  });
});

describe("each group's count after a search (TASK-176)", () => {
  const SEARCHED: SearchedGroups = {
    q: EXAMPLE,
    mode: "native",
    total: 67,
    groups: counted(EXAMPLE, [
      [6343, 139],
      [529, 2337],
      [1, 1],
    ]),
  };

  it("shows each group's count as the API sent it, beside the search's total, as plain text", async () => {
    show(EXAMPLE, SEARCHED);
    await pass(10);
    const [g1, g2, g3] = groups();
    if (g1 === undefined || g2 === undefined || g3 === undefined) throw new Error("three groups");
    // (`·` is hidden from a screen reader, which hears the `;` instead)
    expect(within(g1).getByText(/this group alone/u).textContent).toBe(
      "6,343 papers match this group alone ·; 139 match the query without it",
    );
    expect(within(g2).getByText(/this group alone/u).textContent).toBe(
      "529 papers match this group alone ·; 2,337 match the query without it",
    );
    expect(within(g3).getByText(/this group alone/u).textContent).toBe(
      "1 paper matches this group alone ·; 1 matches the query without it",
    );
    expect(within(g2).getByText("·").getAttribute("aria-hidden")).toBe("true");
    const note = screen.getByText(NOTE);
    expect(note.textContent).toBe(
      "67 papers match the whole query. Each group shows how many papers match it with the other groups " +
        "removed, and how many match the query without it: the group whose removal adds the most papers " +
        "narrows the search most. The query's limits, leave-out terms and default filters apply to every count.",
    );
    // the counts arrive without focus moving, so a polite status says so
    expect(screen.getByRole("status", { name: "Group counts" }).textContent).toBe(
      "Group counts shown for 3 groups: 67 papers match the whole query.",
    );
    // the count is content of its group, so a screen reader meets it there; the group keeps its name
    expect(g2.getAttribute("aria-label")).toBe("Group 2 of 3, any of: trustworth star, trust");
  });

  it("shows none before a search", async () => {
    show(EXAMPLE, null);
    await pass(10);
    expect(groups()).toHaveLength(3);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(NOTE)).toBeNull();
    expect(screen.getByRole("status", { name: "Group counts" }).textContent).toBe("");
  });

  it("shows none for a draft that is not the searched query: its text, or its mode", async () => {
    show(EXAMPLE, { ...SEARCHED, q: `${EXAMPLE} ` });
    await pass(10);
    expect(groups()).toHaveLength(3);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    cleanup();
    show(EXAMPLE, { ...SEARCHED, mode: "scholar" });
    await pass(10);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(NOTE)).toBeNull();
  });

  it("drops every count at once when a builder edit changes the draft", async () => {
    const { onEdit, rerender } = show(EXAMPLE, SEARCHED);
    await pass(10);
    expect(screen.getAllByText(/this group alone/u)).toHaveLength(3);
    fireEvent.click(screen.getAllByRole("button", { name: "Remove group" })[2] as HTMLElement);
    await pass(10);
    const edited = onEdit.mock.calls[0]?.[0];
    if (edited === undefined || edited === EXAMPLE) throw new Error("the edit rewrote the draft");
    rerender(
      <ConceptBuilder
        text={edited}
        mode="native"
        onEdit={onEdit}
        onEditInText={() => {}}
        focusOnOpen={false}
        onFocused={() => {}}
        searched={SEARCHED}
      />,
    );
    await pass(10);
    expect(groups()).toHaveLength(2);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(NOTE)).toBeNull();
  });

  it("shows none for a query that is not an AND of groups", async () => {
    const one: SearchedGroups = {
      q: "trust",
      mode: "native",
      total: 412,
      groups: { counts: [], groups_total: 1, limit: 10, not_counted: "fewer_than_two_groups" },
    };
    show("trust", one);
    await pass(10);
    expect(groups()).toHaveLength(1);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.queryByText(/whole query|aren't shown/u)).toBeNull();
  });

  it("says why a query of more groups than the site counts has none", async () => {
    const over: SearchedGroups = {
      q: EXAMPLE,
      mode: "native",
      total: 67,
      groups: { counts: [], groups_total: 3, limit: 2, not_counted: "too_many_groups" },
    };
    show(EXAMPLE, over);
    await pass(10);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.getAllByText(/Group counts aren't shown/u).map((e) => e.textContent)).toEqual([
      "Group counts aren't shown: this query has 3 groups, and this site counts at most 2.",
      "Group counts aren't shown: this query has 3 groups, and this site counts at most 2.", // the status
    ]);
  });

  it.each([
    [
      "too_costly",
      "Group counts aren't shown: counting each group of this query would read more terms than this site allows. Shorten the leave-out terms or use longer wildcard stems to see them.",
    ],
    [
      "busy",
      "Group counts weren't computed for this search: the site was busy counting for other searches. Search again to see them.",
    ],
    ["count_failed", "Group counts couldn't be computed for this search. Search again to see them."],
    ["timed_out", "Group counts weren't ready in time for this search. Search again to see them."],
    ["a_reason_added_later", "Group counts couldn't be computed for this search. Search again to see them."],
  ])("says so when the search has no counts because of %s", async (reason, text) => {
    const none: SearchedGroups = {
      q: EXAMPLE,
      mode: "native",
      total: 67,
      // the reason is an open set: one this build doesn't know is worded as a failure
      groups: { counts: [], groups_total: 3, limit: 10, not_counted: reason as GroupCounts["not_counted"] },
    };
    show(EXAMPLE, none);
    await pass(10);
    expect(groups()).toHaveLength(3);
    expect(screen.queryByText(/this group alone/u)).toBeNull();
    expect(screen.getByRole("status", { name: "Group counts" }).textContent).toBe(text);
    expect(screen.getAllByText(text)).toHaveLength(2);
  });

  it("shows the count of each part that fits under the read-only notice", async () => {
    const searched: SearchedGroups = {
      q: PARTLY,
      mode: "native",
      total: 3,
      groups: counted(PARTLY, [
        [40, 7],
        [12, 9],
      ]),
    };
    show(PARTLY, searched);
    await pass(10);
    const parts = screen.getByRole("region", { name: "Parts that fit the builder" });
    const [g1, ...rest] = within(parts).getAllByRole("group");
    expect(rest).toHaveLength(0);
    expect(within(g1 as HTMLElement).getByText(/this group alone/u).textContent).toBe(
      "40 papers match this group alone ·; 7 match the query without it",
    );
    expect(within(parts).getByText(NOTE).textContent).toContain("3 papers match the whole query.");
    expect(parts.textContent).not.toContain("12 papers");
  });
});
