// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  space = 19,
  LParen = 1,
  RParen = 2,
  Pipe = 3,
  And = 4,
  Or = 5,
  Not = 6,
  Minus = 7,
  Near = 8,
  BadNear = 9,
  Field = 10,
  UnknownField = 11,
  Phrase = 12,
  Range = 13,
  Wildcard = 14,
  Word = 15,
  Query = 16
