// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {queryTokens} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQVQPOOOOQP'#Cq'#CqOOQP'#Cm'#CmQVQPOOOOQP-E6k-E6k",
  stateData: "!W~OcOS~OPPOQPORPOSPOTPOUPOVPOWPOXPOYPOZPO[PO]PO^PO_PO~O",
  goto: "qfPPPPPPPPPPPPPPPPPgPPPmQRORSRTQOR",
  nodeNames: "⚠ LParen RParen Pipe And Or Not Minus Near BadNear Field UnknownField Phrase Range Wildcard Word Query",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [queryTokens],
  topRules: {"Query":[0,16]},
  tokenPrec: 0
})
