import { describe, expect, it } from "vitest";
import { clip } from "./clip";
import golden from "./clip-golden.json";

// Each case's output is what the backend's `diagnostics.clip` gives for the same input and width, generated by
// `backend/tests/contract/test_frontend_clip_golden.py` (which fails while this file is stale), so a refusal
// here and an API message quote a value alike (TASK-144, TASK-160).
const CASES = golden.cases.map((c) => ({ ...c, input: String.fromCodePoint(...c.input) }));

describe("clip (the frontend twin of diagnostics.clip)", () => {
  it("has the backend's cases", () => {
    expect(CASES.length).toBeGreaterThan(20);
  });

  it.each(CASES)("quotes $input (width $width) as the backend does", ({ input, width, output }) => {
    expect(width === null ? clip(input) : clip(input, width)).toBe(output);
  });
});
